In [4]:
import pandas as pd
import numpy as np
import gensim

In [5]:
# Load the pre-trained word2vec model
model_path = 'GoogleNews-vectors-negative300.bin'
model = gensim.models.KeyedVectors.load_word2vec_format(model_path, binary=True)

In [6]:
# Define the list of words for bed sizes
# bed_size_key_words = ['Twin',  
#     'Queen', 
#     'King' ,
#     'California King',
#     'Twin XL' ,
#     'Full' ,
#     'Single' ,
#     'Sofa' ,
#     'Rollaway' ,
#     'Bunk' ,
#     'Murphy' ,
#     'Trundle' ,
#     'Daybed',
#     'Crib' , 'Pack' 
#     ,'Air Mattress', 
#     'Twin Beds', 
#     'Double Bed', 
#     'Queen Beds',
#     'Double Bed', 
#     'Queen Bed',                  
#     'King Beds' ,
#     'California King Beds',
#     'Twin XL Beds' ,
#     'Full Beds' ,
#     'Single Beds' ,
#     'Sofa Beds' ,
#     'Rollaway Beds' ,
#     'Bunk Beds' ,
#     'Murphy Beds' ,
#     'Trundle Beds' ,
#     'Daybed Beds',
#         'Crib Beds' , 'Pack Beds'                  
#  ]



# room_style_key_words = [
#     'Queen',
#     'Apartment',
#     'Standard',
#     'Suite',
#     'Deluxe',
#     'Double',
#     'Executive',
#     'Leisure',
#     'Club',
#     'Superior',
#     'Connecting',
#     'Accessible',
#     'Family',
#     'Pet-Friendly',
#     'Jacuzzi',
#     'Adjoining',
#     'Loft',
#     'Penthouse Suite',
#     'Standard Room',
#     'Suite Room',
#     'Deluxe Room',
#     'Executive Room',
#     'Club Room',
#     'Superior Room',
#     'Connecting Room',
#     'Accessible Room',
#     'Family Room',
#     'Pet-Friendly Room',
#     'Jacuzzi Room',
#     'Adjoining Room',
#     'Loft Room',
#     'Penthouse Suite Room'
    
# ]

In [7]:
bed_size_key_words = [ 
    'Queen', 
    'King' ,
    'California King',
    'Twin XL' ,
    'Full' ,
    'Single' ,
    'Twin', 
    'Sofa' ,
    'Rollaway' ,
    'Bunk' ,
    'Murphy' ,
    'Trundle' ,
    #'Premium',
    'Daybed',
    'Queens',
    'Crib' , 'Pack' 
    ,'Air Mattress', 
    'Twin Beds'

 ]



room_style_key_words = [
    'Standard',
    'Deluxe',
    'Joint',
    'Superior',
    'Studio',
    'Premium',
    'Dormitory',
    'Economy',
    'Connecting',
    'Junior Suite ',
    'Suite Club',
    'Suite Premium',
    'Suite Presidential',
    'Studio Standard',
    'Studio Delux',
    'Studio Suite',
    'Studio Superior',
    'Suite'
    'Apartment',
    'Premier',
    'Executive',
    'Cabana',
    'Club',
    'Villa',
    'Penthouse',
    'Leisure'
]

In [8]:
df = pd.read_csv("merged.csv")

/tmp/ipykernel_8541/1330870347.py:1: DtypeWarning: Columns (4,7,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("merged.csv")

In [9]:
# df = pd.read_csv("merged.csv")
# df = df.head(100)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 16 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   search_dt              1048575 non-null  object
 1   checkin_date           1048575 non-null  object
 2   Check-out Date         1048575 non-null  object
 3   property_name          1048575 non-null  object
 4   Star Rating(out of 5)  883587 non-null   object
 5   room_type              1048258 non-null  object
 6   room_rate              1029822 non-null  object
 7   Review Score           937870 non-null   object
 8   location_desc          1048575 non-null  object
 9   Distance               1048575 non-null  object
 10  Room Details           1043447 non-null  object
 11  Breakfast              197022 non-null   object
 12  Cancelations           491596 non-null   object
 13  Availability           472387 non-null   object
 14  Unnamed: 14            214 non-null      object
 15  Unnamed: 15            132 non-null      object
dtypes: object(16)
memory usage: 128.0+ MB

In [8]:
#df['room_type'] = df['HotelBeds RoomName']

In [11]:
replacements = {"Two": "2", "Three": "3", "1":" 1 ", "2":" 2 ", "3":" 3 ", "-":" " ,"/":" / " }

# replace values in the 'room_type' column using the dictionary
df['room_type'] = df['room_type'].replace(replacements, regex=True)

In [12]:
df['room_type'] = df['room_type'].str.title()

In [13]:
df.head(4)

,search_dt,checkin_date,Check-out Date,property_name,Star Rating(out of 5),room_type,room_rate,Review Score,location_desc,Distance,Room Details,Breakfast,Cancelations,Availability,Unnamed: 14,Unnamed: 15
0,02-16-2023 18:00:15,2023-02-16,2023-02-17,Red Roof Inn PLUS+ San Antonio Downtown - Rive...,3.0,Superior King Room Disability Access Roll In S...,NaN,6.7,"Downtown - Riverwalk, San Antonio","Downtown - Riverwalk, San Antonio",1 extra-large double bed,NaN,NaN,NaN,NaN,NaN
1,02-16-2023 18:00:15,2023-02-16,2023-02-17,Clarion Pointe near Medical Center,2.0,King Room Accessible / Non Smoking,US$59,7.2,"Northwest San Antonio, San Antonio","Northwest San Antonio, San Antonio",1 extra-large double bed,yes,FREE cancellation | No prepayment needed,NaN,NaN,NaN
2,02-16-2023 18:00:15,2023-02-16,2023-02-17,Comfort Suites Medical Center Near Six Flags,3.0,King Suite Accessible / Non Smoking,US$76,7.8,"Northwest San Antonio, San Antonio","Northwest San Antonio, San Antonio","Private suite2 beds (1 extra-large double, 1 s...",yes,NaN,Only 6 left at this price on our site,NaN,NaN
3,02-16-2023 18:00:15,2023-02-16,2023-02-17,Comfort Inn & Suites San Antonio Airport,3.0,King Room Mobility And Hearing Accessible / ...,US$79,7.4,"North San Antonio - SAT, San Antonio","North San Antonio - SAT, San Antonio",1 extra-large double bed,yes,NaN,NaN,NaN,NaN

In [15]:
# Define a function to tokenize the room types and extract bigrams and trigrams
def get_ngrams(room_type):
    tokens = room_type.split()
    bigrams = [' '.join(tokens[i:i+2]) for i in range(len(tokens)-1)]
    trigrams = [' '.join(tokens[i:i+3]) for i in range(len(tokens)-2)]
    return tokens + bigrams + trigrams

df['room_type'] = df['room_type'].astype(str)
# Apply the get_ngrams function to the room types column
df['ngrams'] = df['room_type'].apply(get_ngrams)

In [16]:
df['ngrams'][0]

['Superior',
 'King',
 'Room',
 'Disability',
 'Access',
 'Roll',
 'In',
 'Shower',
 'Smoke',
 'Free',
 'Superior King',
 'King Room',
 'Room Disability',
 'Disability Access',
 'Access Roll',
 'Roll In',
 'In Shower',
 'Shower Smoke',
 'Smoke Free',
 'Superior King Room',
 'King Room Disability',
 'Room Disability Access',
 'Disability Access Roll',
 'Access Roll In',
 'Roll In Shower',
 'In Shower Smoke',
 'Shower Smoke Free']

In [17]:
import spacy

nlp = spacy.load("en_core_web_sm")


def get_bed_count(trigrams):
    for trigram in trigrams:
        if "Bed" in trigram or "Beds" in trigram or "bed" in trigram or "beds" in trigram:
            doc = nlp(trigram)
            for token in doc:
                if token.is_digit:
                    return int(token.text)
    return 1

df["bed_count"] = df["ngrams"].apply(get_bed_count)

2023-05-11 09:14:15.849509: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-11 09:14:32.608810: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-05-11 09:14:32.609199: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-05-11 09:14:32.609224: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-05-11 09:14:38.738640: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-05-11 09:14:38.746181: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-05-11 09:14:38.746239: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ushan-Inspiron-5558): /proc/driver/nvidia/version does not exist

In [18]:
df['room_type_1'] = df['room_type']

In [19]:
df.tail(2)

,search_dt,checkin_date,Check-out Date,property_name,Star Rating(out of 5),room_type,room_rate,Review Score,location_desc,Distance,Room Details,Breakfast,Cancelations,Availability,Unnamed: 14,Unnamed: 15,ngrams,bed_count,room_type_1
1048573,02-15-2023 20:03:25,2023-02-17,2023-02-18,Washington Marriott Georgetown,4,"Guest Room, 1 King",US$269,7.8,"Northwest, Washington","Northwest, Washington",1 extra-large double bed,NaN,FREE cancellation | No prepayment needed,Only 5 rooms left at this price on our site,NaN,NaN,"[Guest, Room,, 1, King, Guest Room,, Room, 1, ...",1,"Guest Room, 1 King"
1048574,02-15-2023 20:03:25,2023-02-17,2023-02-18,"Coda on Half, a Placemakr Experience",4,One Bedroom Apartment,US$218,9.1,"Southeast, Washington","Southeast, Washington",Entire apartment | 1 bedroom | 1 living room |...,NaN,NaN,Only 1 left at this price on our site,NaN,NaN,"[One, Bedroom, Apartment, One Bedroom, Bedroom...",1,One Bedroom Apartment

In [20]:
import re

# loop through the rows of the dataframe
for index, row in df.iterrows():
    room_type = row['room_type']
    
    # extract the room style and bed size
    room_style = ''
    bed_size = ''
    
    if 'Double' in room_type:
        room_style = 'Double'
        bed_size = room_type.replace('Double', '').strip()
    elif 'Triple' in room_type:
        room_style = 'Triple'
        bed_size = room_type.replace('Triple', '').strip()
    elif 'Quadruple' in room_type:
        room_style = 'Quadruple'
        bed_size = room_type.replace('Quadruple', '').strip()
    else:
        room_style = ''
        bed_size = room_type
        
    
    # update the row with the new information
    df.at[index, 'room_style_1'] = room_style
    df.at[index, 'room_type_1'] = bed_size

In [ ]:
df['ngrams'][0]

In [22]:
bed_size_key_words

['Queen',
 'King',
 'California King',
 'Twin XL',
 'Full',
 'Single',
 'Twin',
 'Sofa',
 'Rollaway',
 'Bunk',
 'Murphy',
 'Trundle',
 'Daybed',
 'Queens',
 'Crib',
 'Pack',
 'Air Mattress',
 'Twin Beds']

In [56]:
import pandas as pd
import re

# Define a regular expression to match trigrams that end with "bed" or "beds"
regex = re.compile(r'\b\w+\s+\w+\s+(beds?|sofa bed)\b')

# Define a function to find the best matching bed size keyword for a given ngram
def get_best_match(ngram):
    matches = []
    for bed_size in bed_size_key_words:
        if bed_size in ngram:
            matches.append(bed_size)
    if len(matches) == 0:
        return None
    elif len(matches) == 1:
        return matches[0]
    else:
        # If there are multiple matches, return the longest match
        return max(matches, key=len)

# Find the best matching bed size keyword for each ngram and add it to a new column
df['bed_size'] = df['ngrams'].apply(lambda x: get_best_match(x))

In [57]:
df.head(100)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier Bed,,King,Premier,NaN,2.0
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 Beds,,King,,NaN,4.0
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,Apartment Size Bed,,King,,NaN,2.0
3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Size Bed,Double,Queen,Double,2.0,2.0
4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,Suite Size Bed,,King,,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,15780037,145605,HotelBeds,15780037-9,DBL.EY,DOUBLE ECONOMY,Economy,Double Economy,"[Double, Economy, Double Economy]",1,Economy,Double,None,Economy,2.0,2.0
96,15780037,145605,HotelBeds,15780037-10,DBL.KG,DOUBLE KING SIZE BED,King Room,Double Size Bed,"[Double, King, Size, Bed, Double King, King Si...",1,Size Bed,Double,King,Double,2.0,2.0
97,15780037,145605,HotelBeds,15780037-11,SUI.LO,SUITE LOFT,Loft Suite,Suite Loft,"[Suite, Loft, Suite Loft]",1,Suite Loft,,None,,NaN,1.0
98,15780037,145605,HotelBeds,15780037-12,ROO.PE,Room PREMIER,Premier,Room Premier,"[Room, Premier, Room Premier]",1,Room Premier,,None,Premier,NaN,2.0
99,15780037,145605,HotelBeds,15780037-12,DBL.PE-5,DOUBLE PREMIER,Premier,Double Premier,"[Double, Premier, Double Premier]",1,Premier,Double,None,Premier,2.0,2.0

In [58]:
num_null = df['bed_size'].isnull().sum()
num_null

1037

In [59]:

# Loop through each row of the DataFrame
for index, row in df.iterrows():
    bed_size = row['bed_size']
    room_type = row['room_type']
    
    # Check if the bed_size is not None
    if bed_size is not None:
        # Remove the bed_size keyword from the room_type string
        room_type = room_type.replace(bed_size, '').strip()
        room_type = room_type.replace('beds', '').strip()
        
        # Update the room_type column in the DataFrame
        df.at[index, 'room_type'] = room_type

In [60]:
df.head(2)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier Bed,,King,Premier,NaN,2.0
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 Beds,,King,,NaN,4.0

In [61]:

# Define a function to find the best matching key word for a list of ngrams
def get_best_match(ngrams, key_words):
    best_match = ''
    best_similarity = -1
    for ngram in ngrams:
        if ngram in model:
            for key_word in key_words:
                # Split key word into individual words
                key_word_tokens = key_word.split()
                # Check if all words in key word are present in ngram
                if all(token in ngram.split() for token in key_word_tokens):
                    similarity = model.similarity(ngram, key_word)
                    if similarity > best_similarity:
                        best_similarity = similarity
                        best_match = key_word
    return best_match



# Apply the get_best_match function to the ngrams column for bed sizes
#df['bed_size'] = df['ngrams'].apply(lambda x: get_best_match(x, bed_size_key_words))

# Apply the get_best_match function to the ngrams column for room styles
df['room_style'] = df['ngrams'].apply(lambda x: get_best_match(x, room_style_key_words))

In [62]:
df.tail(5)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
1952,41268569,907505,HotelBeds,41268569-11,TWN.H6,2 QUEEN BEDS ACCESSIBLE ROOM,"Room - 2 Queen, Accessible",2 Beds Accessible Room,"[2, Queen, Beds, Accessible, Room, 2 Queen, Qu...",2,2 Beds Accessible Room,,Queen,,NaN,4.0
1953,41268569,907505,HotelBeds,41268569-12,TWN.2Q-CV,2 QUEEN BED CITY VIEW ROOM,"Room - 2 Queen, City View",2 Bed City View Room,"[2, Queen, Bed, City, View, Room, 2 Queen, Que...",2,2 Bed City View Room,,Queen,,NaN,4.0
1954,41268569,907505,HotelBeds,41268569-13,ROO.CV,1 BED ROOM CITY VIEW WITH BALCONY,"Room With City View, Balcony",1 Bed Room City View With Balcony,"[1, Bed, Room, City, View, With, Balcony, 1 Be...",1,1 Bed Room City View With Balcony,,None,,NaN,1.0
1955,41268569,907505,HotelBeds,41268569-14,SUI.B1-KG,1 KING BED 1 BEDROOM SUITE,"Suite, 1 Bedroom",1 Bed 1 Bedroom Suite,"[1, King, Bed, 1, Bedroom, Suite, 1 King, King...",1,1 Bed 1 Bedroom Suite,,King,,NaN,2.0
1956,41268569,907505,HotelBeds,41268569-15,SUI.KG,1 KING BED 1 BEDROOM SUITE WITH BALCONY,"Suite, 1 Bedroom, Balcony",1 Bed 1 Bedroom Suite With Balcony,"[1, King, Bed, 1, Bedroom, Suite, With, Balcon...",1,1 Bed 1 Bedroom Suite With Balcony,,King,,NaN,2.0

In [63]:
#df['room_type_1'] = df['room_type']

In [64]:
# df['Vevotech Naming'] = df['Vervotech MappedStandardName']
# df['hotelRoomType'] = df['room_type']

In [65]:
df.head(100)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier Bed,,King,Premier,NaN,2.0
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 Beds,,King,,NaN,4.0
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,Apartment Size Bed,,King,,NaN,2.0
3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Size Bed,Double,Queen,,2.0,2.0
4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,Suite Size Bed,,King,,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,15780037,145605,HotelBeds,15780037-9,DBL.EY,DOUBLE ECONOMY,Economy,Double Economy,"[Double, Economy, Double Economy]",1,Economy,Double,None,Economy,2.0,2.0
96,15780037,145605,HotelBeds,15780037-10,DBL.KG,DOUBLE KING SIZE BED,King Room,Double Size Bed,"[Double, King, Size, Bed, Double King, King Si...",1,Size Bed,Double,King,,2.0,2.0
97,15780037,145605,HotelBeds,15780037-11,SUI.LO,SUITE LOFT,Loft Suite,Suite Loft,"[Suite, Loft, Suite Loft]",1,Suite Loft,,None,,NaN,1.0
98,15780037,145605,HotelBeds,15780037-12,ROO.PE,Room PREMIER,Premier,Room Premier,"[Room, Premier, Room Premier]",1,Room Premier,,None,Premier,NaN,2.0
99,15780037,145605,HotelBeds,15780037-12,DBL.PE-5,DOUBLE PREMIER,Premier,Double Premier,"[Double, Premier, Double Premier]",1,Premier,Double,None,Premier,2.0,2.0

In [66]:
# fill empty values in the "bed_type" column with corresponding values in "bed_type_1"
#df['room_style'] = df.apply(lambda x: x['room_style_1'] if x['room_style'] == '' else x['room_style'], axis=1)

In [67]:
df.head(5)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier Bed,,King,Premier,NaN,2.0
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 Beds,,King,,NaN,4.0
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,Apartment Size Bed,,King,,NaN,2.0
3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Size Bed,Double,Queen,,2.0,2.0
4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,Suite Size Bed,,King,,NaN,2.0

In [68]:

# add a new column "no_of_person" with values from "bed_count" column
#df['no_of_person'] = df['bed_count']

df.loc[df['room_style_1'] == 'Double', 'no_of_person'] = 2
df.loc[df['room_style_1'] == 'Triple', 'no_of_person'] = 3
df.loc[df['room_style_1'] == 'Quadruple', 'no_of_person'] = 4

In [69]:
# update the no_of_people column where room_style is king, queen or premium
df.loc[df['bed_size'].isin(['King', 'Queen', 'premium','Premium',  'Full', 'Sofa', 'Bunk']), 'no_of_people'] = df['bed_count'] * 2

# update the no_of_people column for other room_style values
df.loc[~df['bed_size'].isin(['King', 'Queen', 'premium','Premium',  'Full', 'Sofa', 'Bunk']), 'no_of_people'] = df['bed_count'] * 1

In [70]:
df.head(15)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier Bed,,King,Premier,NaN,2.0
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 Beds,,King,,NaN,4.0
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,Apartment Size Bed,,King,,NaN,2.0
3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Size Bed,Double,Queen,,2.0,2.0
4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,Suite Size Bed,,King,,NaN,2.0
5,15324900,141230,HotelBeds,15324900-1,DBL.2Q-DX,2 Queen Beds Deluxe Nonsmoke,"Deluxe, 2 Queen",2 Beds Deluxe Nonsmoke,"[2, Queen, Beds, Deluxe, Nonsmoke, 2 Queen, Qu...",2,2 Beds Deluxe Nonsmoke,,Queen,Deluxe,NaN,4.0
6,15324900,141230,HotelBeds,15324900-1,ROO.2Q-DX,2 QUEEN BEDS DELUXE NONSMOKE,"Deluxe, 2 Queen",2 Beds Deluxe Nonsmoke,"[2, Queen, Beds, Deluxe, Nonsmoke, 2 Queen, Qu...",2,2 Beds Deluxe Nonsmoke,,Queen,Deluxe,NaN,4.0
7,15324900,141230,HotelBeds,15324900-2,DBL.DX-KG,King Deluxe Accessible Roll Shwr Nosmk,"Deluxe, King, Accessible",Deluxe Accessible Roll Shwr Nosmk,"[King, Deluxe, Accessible, Roll, Shwr, Nosmk, ...",1,Deluxe Accessible Roll Shwr Nosmk,,King,Deluxe,NaN,2.0
8,15324900,141230,HotelBeds,15324900-3,DBL.KG,KING LEISURE NONSMOKE,King Room,Leisure Nonsmoke,"[King, Leisure, Nonsmoke, King Leisure, Leisur...",1,Leisure Nonsmoke,,King,Leisure,NaN,2.0
9,15324900,141230,HotelBeds,15324900-4,DBL.H6-KG,DOUBLE Accessible KING SIZE BED,"King Room, Accessible",Double Accessible Size Bed,"[Double, Accessible, King, Size, Bed, Double A...",1,Accessible Size Bed,Double,King,,2.0,2.0
10,15324900,141230,HotelBeds,15324900-5,DBL.CV-KG,DOUBLE CITY VIEW KING BED,"King Room, City View",Double City View Bed,"[Double, City, View, King, Bed, Double City, C...",1,City View Bed,Double,King,,2.0,2.0
11,15324900,141230,HotelBeds,15324900-6,QUA.2Q-NM,QUADRUPLE 2 QUEEN BEDS NON SMOKING,Quadruple Room,Quadruple 2 Beds Non Smoking,"[Quadruple, 2, Queen, Beds, Non, Smoking, Quad...",2,2 Beds Non Smoking,Quadruple,Queen,,4.0,4.0
12,15324900,141230,HotelBeds,15324900-7,DBL.NM-QN,1 QUEEN BED NONSMOKING,Queen Room,1 Bed Nonsmoking,"[1, Queen, Bed, Nonsmoking, 1 Queen, Queen Bed...",1,1 Bed Nonsmoking,,Queen,,NaN,2.0
13,15324900,141230,HotelBeds,15324900-7,ROO.NM-QN,Room QUEEN BED NON SMOKING,Queen Room,Room Bed Non Smoking,"[Room, Queen, Bed, Non, Smoking, Room Queen, Q...",1,Room Bed Non Smoking,,Queen,,NaN,2.0
14,15324900,141230,HotelBeds,15324900-7,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Size Bed,Double,Queen,,2.0,2.0

In [71]:
df['bed_size'].unique()

array(['King', 'Queen', None, 'Single', 'Twin', 'Queens', 'Full', 'Sofa',
       'Bunk'], dtype=object)

In [72]:
# replace blank values in room_style column with room_style_1 values
df.loc[df['room_style'] == '', 'room_style'] = df.loc[df['room_style'] == '', 'room_style_1']

In [73]:
# find the maximum value between no_of_person and no_of_people columns
df['no_of_people'] = df[['no_of_person', 'no_of_people']].max(axis=1)

In [74]:
# replace bed_count with 2 where no_of_people is 4 and bed_count is 1
df.loc[(df['no_of_people'] == 4) & (df['bed_count'] == 1), 'bed_count'] = 2

In [75]:
# replace null values in bed_size column with room_style_1 values
df.loc[(df['bed_size'].isnull()) & (df['room_style_1'].isin(['Double', 'Triple'])), 'bed_size'] = df['room_style_1']

In [76]:
# replace null values in bed_size column with 'King' if room_style column has any of the specified values
df.loc[(df['bed_size'].isnull()) & (df['room_style'].isin(['Apartment', 'Suite', 'Leisure', 'Standard', 'Executive', 'Economy', 'Premier', 'Superior', 'Studio', 'Villa', 'Penthouse'])), 'bed_size'] = 'King'

df.loc[(df['bed_size'].isnull()) & (df['room_style'].isin(['Deluxe', 'Club'])), 'bed_size'] = 'Queen'

df.loc[(df['bed_size'].isnull()) & (df['room_style'].isin(['Dormitory' ])), 'bed_size'] = 'Single'

In [77]:
# update the 'no_of_people' column based on the condition
df.loc[(df['no_of_people']/df['bed_count'] == 1) & (df['bed_size'].isin(['King', 'Queen','Queens','Twin', 'Double'])), 'no_of_people'] = df['bed_count'] * 2

In [78]:
df['bed_size'].unique()

array(['King', 'Queen', None, 'Double', 'Single', 'Twin', 'Triple',
       'Queens', 'Full', 'Sofa', 'Bunk'], dtype=object)

In [79]:
# df1 = df[(df['bed_count'] == 1)]
# df1

In [80]:
df1 = df[(df['room_style'] == 'Penthouse') & (df['bed_size'].isnull())]
df1

Empty DataFrame
Columns: [Vervotech ID, SupplierHotelId, SupplierName, GroupId, HotelBeds RoomCode, HotelBeds RoomName, Vervotech MappedStandardName, room_type, ngrams, bed_count, room_type_1, room_style_1, bed_size, room_style, no_of_person, no_of_people]
Index: []

In [81]:
(df['no_of_people'][110] /df['bed_count'][110])== 1

True

In [82]:
df1 = df[(df['bed_size'] == 'Twin') & (df['bed_count'] == 2) ]
df1

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
57,15471297,45947,HotelBeds,15471297-16,TWN.2D-CV,TWIN CITY VIEW 2 DOUBLE BEDS,"Room - 2 Double, City View",City View 2 Double Beds,"[Twin, City, View, 2, Double, Beds, Twin City,...",2,City View 2 Beds,Double,Twin,Double,2.0,4.0
145,15382506,42990,HotelBeds,15382506-7,TWN.2D,TWIN 2 DOUBLE BEDS,Room - 2 Double,2 Double Beds,"[Twin, 2, Double, Beds, Twin 2, 2 Double, Doub...",2,2 Beds,Double,Twin,Double,2.0,4.0
155,15382506,42990,HotelBeds,15382506-14,DBT.2D-SU,Double or Twin SUPERIOR 2 DOUBLE BEDS,"Superior, 2 Double",Double Or Superior 2 Double Beds,"[Double, Or, Twin, Superior, 2, Double, Beds, ...",2,Or Superior 2 Beds,Double,Twin,Superior,2.0,4.0
157,15382506,42990,HotelBeds,15382506-14,TWN.2D-SU,TWIN SUPERIOR 2 DOUBLE BEDS,"Superior, 2 Double",Superior 2 Double Beds,"[Twin, Superior, 2, Double, Beds, Twin Superio...",2,Superior 2 Beds,Double,Twin,Superior,2.0,4.0
413,38380068,589938,HotelBeds,38380068-16,DBT.2D-6,Double or Twin 2 DOUBLE BEDS,Room - 2 Queen,Double Or 2 Double Beds,"[Double, Or, Twin, 2, Double, Beds, Double Or,...",2,Or 2 Beds,Double,Twin,Double,2.0,4.0
435,38751099,13046,HotelBeds,38751099-9,TWN.2D-DX,TWIN DELUXE 2 DOUBLE BEDS,"DELUXE, 2 Double",Deluxe 2 Double Beds,"[Twin, Deluxe, 2, Double, Beds, Twin Deluxe, D...",2,Deluxe 2 Beds,Double,Twin,Deluxe,2.0,4.0
466,38751099,13046,HotelBeds,38751099-35,TWN.2D,TWIN 2 DOUBLE BEDS,Room - 2 Double,2 Double Beds,"[Twin, 2, Double, Beds, Twin 2, 2 Double, Doub...",2,2 Beds,Double,Twin,Double,2.0,4.0
509,38751099,13046,HotelBeds,38751099-69,DBT.2D-SU,Double or Twin SUPERIOR 2 DOUBLE BEDS,"SUPERIOR, 2 Double",Double Or Superior 2 Double Beds,"[Double, Or, Twin, Superior, 2, Double, Beds, ...",2,Or Superior 2 Beds,Double,Twin,Superior,2.0,4.0
615,39091738,16145,HotelBeds,39091738-16,TWN.2D,TWIN 2 DOUBLE BEDS,Room - 2 Double,2 Double Beds,"[Twin, 2, Double, Beds, Twin 2, 2 Double, Doub...",2,2 Beds,Double,Twin,Double,2.0,4.0
633,39091739,16182,HotelBeds,39091739-7,TWN.2D-EJ,TWIN EXECUTIVE 2 DOUBLE BEDS,"Executive, 2 Double",Executive 2 Double Beds,"[Twin, Executive, 2, Double, Beds, Twin Execut...",2,Executive 2 Beds,Double,Twin,Executive,2.0,4.0
721,39600932,251774,HotelBeds,39600932-14,TWN.2D,TWIN 2 DOUBLE BEDS,Room - 2 Double,2 Double Beds,"[Twin, 2, Double, Beds, Twin 2, 2 Double, Doub...",2,2 Beds,Double,Twin,Double,2.0,4.0
722,39600932,251774,HotelBeds,39600932-15,TWN.2D-CV,TWIN CITY VIEW 2 DOUBLE BEDS,"Room - 2 Double, City View",City View 2 Double Beds,"[Twin, City, View, 2, Double, Beds, Twin City,...",2,City View 2 Beds,Double,Twin,Double,2.0,4.0
751,39601097,426321,HotelBeds,39601097-6,TWN.2D-CV,TWIN CITY VIEW 2 DOUBLE BEDS,"Room - 2 Double, City View",City View 2 Double Beds,"[Twin, City, View, 2, Double, Beds, Twin City,...",2,City View 2 Beds,Double,Twin,Double,2.0,4.0
871,39603752,251781,HotelBeds,39603752-7,TWN.2D,TWIN 2 DOUBLE BEDS,Room - 2 Double,2 Double Beds,"[Twin, 2, Double, Beds, Twin 2, 2 Double, Doub...",2,2 Beds,Double,Twin,Double,2.0,4.0
1013,39626628,278222,HotelBeds,39626628-4,TWN.2D,TWIN 2 DOUBLE BEDS,Room - 2 Double,2 Double Beds,"[Twin, 2, Double, Beds, Twin 2, 2 Double, Doub...",2,2 Beds,Double,Twin,Double,2.0,4.0
1114,39643859,39219,HotelBeds,39643859-14,TWN.2D,TWIN 2 DOUBLE BEDS,Room - 2 Double,2 Double Beds,"[Twin, 2, Double, Beds, Twin 2, 2 Double, Doub...",2,2 Beds,Double,Twin,Double,2.0,4.0
1215,39649457,16836,HotelBeds,39649457-12,TWN.2D-1,TWIN 2 DOUBLE BEDS,Room - 2 Double,2 Double Beds,"[Twin, 2, Double, Beds, Twin 2, 2 Double, Doub...",2,2 Beds,Double,Twin,Double,2.0,4.0
1231,39650469,16137,HotelBeds,39650469-3,TWN.2D-DX,TWIN DELUXE 2 DOUBLE BEDS,"Deluxe, 2 Double",Deluxe 2 Double Beds,"[Twin, Deluxe, 2, Double, Beds, Twin Deluxe, D...",2,Deluxe 2 Beds,Double,Twin,Deluxe,2.0,4.0
1303,39658032,29251,HotelBeds,39658032-5,TWN.2D-DX,Twin Deluxe 2 double beds,"Deluxe, 2 Double",Deluxe 2 Double Beds,"[Twin, Deluxe, 2, Double, Beds, Twin Deluxe, D...",2,Deluxe 2 Beds,Double,Twin,Deluxe,2.0,4.0
1304,39658032,29251,HotelBeds,39658032-5,DBT.2D-DX,Double or Twin DELUXE 2 DOUBLE BEDS,"Deluxe, 2 Double",Double Or Deluxe 2 Double Beds,"[Double, Or, Twin, Deluxe, 2, Double, Beds, Do...",2,Or Deluxe 2 Beds,Double,Twin,Deluxe,2.0,4.0
1366,39664611,417318,HotelBeds,39664611-3,TWN.2B,TWIN 2 BEDS,DoubleOrTwin Room,2 Beds,"[Twin, 2, Beds, Twin 2, 2 Beds, Twin 2 Beds]",2,2 Beds,,Twin,,NaN,4.0
1498,39675048,128424,HotelBeds,39675048-6,TWN.2D,TWIN 2 DOUBLE BEDS,Room - 2 Double,2 Double Beds,"[Twin, 2, Double, Beds, Twin 2, 2 Double, Doub...",2,2 Beds,Double,Twin,Double,2.0,4.0

In [83]:
# group by bed_count, bed_size, room_style and get the count of records
grouped = df.groupby(['bed_count', 'room_style_1', 'bed_size', 'no_of_people']).size().reset_index(name='count')

grouped

    bed_count room_style_1 bed_size  no_of_people  count
0           1                  Full           2.0      8
1           1                  King           2.0    604
2           1                 Queen           2.0    123
3           1                Queens           2.0     18
4           1                Single           1.0     36
5           1                  Sofa           2.0      3
6           1                  Twin           2.0      6
7           1       Double     Bunk           2.0      1
8           1       Double   Double           2.0    314
9           1       Double     King           2.0    152
10          1       Double    Queen           2.0     54
11          1       Double   Single           2.0      3
12          1       Double     Twin           2.0     28
13          1       Triple     King           3.0      1
14          1       Triple    Queen           3.0      1
15          1       Triple   Triple           3.0      9
16          2                  King           4.0      9
17          2                 Queen           4.0     59
18          2                Queens           4.0      1
19          2                  Sofa           4.0      1
20          2                  Twin           4.0      1
21          2       Double   Double           4.0    137
22          2       Double    Queen           4.0     43
23          2       Double     Twin           4.0     21
24          2    Quadruple     King           4.0     10
25          2    Quadruple    Queen           4.0     37
26          2       Triple    Queen           4.0      1
27          2       Triple   Triple           3.0      1

In [84]:
grouped.head(25)

    bed_count room_style_1 bed_size  no_of_people  count
0           1                  Full           2.0      8
1           1                  King           2.0    604
2           1                 Queen           2.0    123
3           1                Queens           2.0     18
4           1                Single           1.0     36
5           1                  Sofa           2.0      3
6           1                  Twin           2.0      6
7           1       Double     Bunk           2.0      1
8           1       Double   Double           2.0    314
9           1       Double     King           2.0    152
10          1       Double    Queen           2.0     54
11          1       Double   Single           2.0      3
12          1       Double     Twin           2.0     28
13          1       Triple     King           3.0      1
14          1       Triple    Queen           3.0      1
15          1       Triple   Triple           3.0      9
16          2                  King           4.0      9
17          2                 Queen           4.0     59
18          2                Queens           4.0      1
19          2                  Sofa           4.0      1
20          2                  Twin           4.0      1
21          2       Double   Double           4.0    137
22          2       Double    Queen           4.0     43
23          2       Double     Twin           4.0     21
24          2    Quadruple     King           4.0     10

In [52]:
df.head(405)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier King Bed,,King,Premier,NaN,2.0
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 King Beds,,King,,NaN,4.0
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,Apartment King Size Bed,,King,,NaN,2.0
3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Queen Size Bed,Double,Queen,Double,2.0,2.0
4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,Suite King Size Bed,,King,,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400,38380068,589938,HotelBeds,38380068-7,DBL.KG-NM,DOUBLE KING BED NON SMOKING,King Room,Double Bed Non Smoking,"[Double, King, Bed, Non, Smoking, Double King,...",1,King Bed Non Smoking,Double,King,Double,2.0,2.0
401,38380068,589938,HotelBeds,38380068-8,DBL.H6-KG,DOUBLE Accessible KING SIZE BED,"King Room, Accessible",Double Accessible Size Bed,"[Double, Accessible, King, Size, Bed, Double A...",1,Accessible King Size Bed,Double,King,Double,2.0,2.0
402,38380068,589938,HotelBeds,38380068-8,ROO.H6-KG,Room Accessible KING SIZE BED,"King Room, Accessible",Room Accessible Size Bed,"[Room, Accessible, King, Size, Bed, Room Acces...",1,Room Accessible King Size Bed,,King,,NaN,2.0
403,38380068,589938,HotelBeds,38380068-9,ROO.ST,STANDARD ROOM,King/Queen Room,Standard Room,"[Standard, Room, Standard Room]",1,Standard Room,,King,Standard,NaN,2.0
404,38380068,589938,HotelBeds,38380068-10,TWN.KG-8,TWIN KING SIZE BED,King/Twin Room,Twin Size Bed,"[Twin, King, Size, Bed, Twin King, King Size, ...",1,Twin King Size Bed,,King,,NaN,2.0

In [50]:
df['room_style_1'][1]

''

In [51]:
empty_values_count = df['room_style'].str.strip().eq('').sum()
empty_values_count

347

In [52]:
df1 = df[(df['room_style_1'] == "Triple") & df['bed_count'] == 1]
df1

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
79,15504023,277857,HotelBeds,15504023-2,TPL.PI,TRIPLE PREMIUM,"Premium, Triple",Triple,"[Triple, Premium, Triple Premium]",1,Premium,Triple,Premium,Triple,3.0,3.0
740,39600932,251774,HotelBeds,39600932-27,TPL.SU,TRIPLE SUPERIOR,"Superior, Triple",Triple Superior,"[Triple, Superior, Triple Superior]",1,Superior,Triple,Triple,Superior,3.0,3.0
741,39600932,251774,HotelBeds,39600932-28,TPL.ST,TRIPLE STANDARD,Triple Room,Triple Standard,"[Triple, Standard, Triple Standard]",1,Standard,Triple,Triple,Standard,3.0,3.0
863,39603646,251773,HotelBeds,39603646-5,TPL.RO,TRIPLE RUN OF HOUSE,"Run Of House, Triple",Triple Run Of House,"[Triple, Run, Of, House, Triple Run, Run Of, O...",1,Run Of House,Triple,Triple,Triple,3.0,3.0
1123,39643859,39219,HotelBeds,39643859-18,TPL.ST,TRIPLE STANDARD,Triple Room,Triple Standard,"[Triple, Standard, Triple Standard]",1,Standard,Triple,Triple,Standard,3.0,3.0
1755,39732127,271877,HotelBeds,39732127-22,TPL.FH-1,Triple Shared Bath,"Triple Room, Shared Bathroom",Triple Shared Bath,"[Triple, Shared, Bath, Triple Shared, Shared B...",1,Shared Bath,Triple,Triple,Triple,3.0,3.0
1855,40050192,13432,HotelBeds,40050192-6,TPL.CB-EJ,TRIPLE CLUB EXECUTIVE,"Club Executive, Triple",Triple Club Executive,"[Triple, Club, Executive, Triple Club, Club Ex...",1,Club Executive,Triple,Triple,Club,3.0,3.0
1858,40050192,13432,HotelBeds,40050192-9,TPL.CB,TRIPLE CLUB,"Club, Triple",Triple Club,"[Triple, Club, Triple Club]",1,Club,Triple,Triple,Club,3.0,3.0
1861,40050192,13432,HotelBeds,40050192-11,TPL.DX-KG,TRIPLE DELUXE KING BED,"Deluxe, King",Triple Deluxe Bed,"[Triple, Deluxe, King, Bed, Triple Deluxe, Del...",1,Deluxe King Bed,Triple,King,Deluxe,3.0,3.0
1868,40050192,13432,HotelBeds,40050192-15,TPL.DX,TRIPLE DELUXE,"Deluxe, Triple",Triple Deluxe,"[Triple, Deluxe, Triple Deluxe]",1,Deluxe,Triple,Triple,Deluxe,3.0,3.0
1906,40050192,13432,HotelBeds,40050192-42,TPL.QN,TRIPLE QUEEN SIZE BED,Triple Room,Triple Size Bed,"[Triple, Queen, Size, Bed, Triple Queen, Queen...",1,Queen Size Bed,Triple,Queen,Triple,3.0,3.0

In [53]:
df

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier King Bed,,King,Apartment,NaN,2.0
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 King Beds,,King,Apartment,NaN,4.0
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,Apartment King Size Bed,,King,Apartment,NaN,2.0
3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Queen Size Bed,Double,Queen,Double,2.0,2.0
4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,Suite King Size Bed,,King,Suite,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1952,41268569,907505,HotelBeds,41268569-11,TWN.H6,2 QUEEN BEDS ACCESSIBLE ROOM,"Room - 2 Queen, Accessible",2 Beds Accessible Room,"[2, Queen, Beds, Accessible, Room, 2 Queen, Qu...",2,2 Queen Beds Accessible Room,,Queen,,NaN,4.0
1953,41268569,907505,HotelBeds,41268569-12,TWN.2Q-CV,2 QUEEN BED CITY VIEW ROOM,"Room - 2 Queen, City View",2 Bed City View Room,"[2, Queen, Bed, City, View, Room, 2 Queen, Que...",2,2 Queen Bed City View Room,,Queen,,NaN,4.0
1954,41268569,907505,HotelBeds,41268569-13,ROO.CV,1 BED ROOM CITY VIEW WITH BALCONY,"Room With City View, Balcony",1 Bed Room City View With Balcony,"[1, Bed, Room, City, View, With, Balcony, 1 Be...",1,1 Bed Room City View With Balcony,,None,,NaN,1.0
1955,41268569,907505,HotelBeds,41268569-14,SUI.B1-KG,1 KING BED 1 BEDROOM SUITE,"Suite, 1 Bedroom",1 Bed 1 Bedroom Suite,"[1, King, Bed, 1, Bedroom, Suite, 1 King, King...",1,1 King Bed 1 Bedroom Suite,,King,Suite,NaN,2.0
1956,41268569,907505,HotelBeds,41268569-15,SUI.KG,1 KING BED 1 BEDROOM SUITE WITH BALCONY,"Suite, 1 Bedroom, Balcony",1 Bed 1 Bedroom Suite With Balcony,"[1, King, Bed, 1, Bedroom, Suite, With, Balcon...",1,1 King Bed 1 Bedroom Suite With Balcony,,King,Suite,NaN,2.0

In [54]:
# df.loc[df['room_style'] == '', 'room_style'] = 'Standard'
# df.loc[df['bed_size'] == '', 'bed_size'] = 'Single'

In [55]:
#df.to_csv("test_5.csv")

In [99]:
from pivottablejs import pivot_ui
pivot_ui(df)

In [3]:
#df = pd.read_csv("test_5.csv")

In [95]:
df.head(5)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier King Bed,,King,Apartment,NaN,2.0
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 King Beds,,King,Apartment,NaN,4.0
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,Apartment King Size Bed,,King,Apartment,NaN,2.0
3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Queen Size Bed,Double,Queen,Double,2.0,2.0
4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,Suite King Size Bed,,King,Suite,NaN,2.0

In [216]:
df1 = pd.read_csv("Niranjani_test_set.csv")
df2 = pd.read_csv("Nileka_test_set.csv")
df3 = pd.read_csv("saumya_test_set_Updated.csv")
df4 = pd.read_csv("Nuwan_test_set.csv")

In [217]:
merged_df = pd.concat([df1, df2, df3, df4], axis=0, ignore_index=True)
merged_df = merged_df.drop(['Unnamed: 11','Unnamed: 9','Unnamed: 10'], axis=1)
df1 = merged_df

# Merge the dataframes based on the index of df and the "Unnamed: 0" column of df1
merged_df = pd.merge(df, df1[['Unnamed: 0', 'Label', 'Remarks']], left_index=True, right_on='Unnamed: 0')

In [218]:
merged_df

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people,Unnamed: 0,Label,Remarks
0,15780037,145605,HotelBeds,15780037-13,DBL.PE,"Premier Skyline View Room, 2 Queen Beds","Premier, 2 Queen, Skyline View","Premier Skyline View Room, 2 Beds","[Premier, Skyline, View, Room,, 2, Queen, Beds...",2,"Premier Skyline View Room, 2 Queen Beds",,Queen,Premier,NaN,4.0,100,-1.0,2 queen bed can accommodate 4 people
1,15780037,145605,HotelBeds,15780037-14,DBL.KG-PE,"Premier Skyline View Room, King Bed","Premier, King, Skyline View","Premier Skyline View Room, Bed","[Premier, Skyline, View, Room,, King, Bed, Pre...",1,"Premier Skyline View Room, King Bed",,King,Premier,NaN,2.0,101,-1.0,no. of people should be 2
2,15780037,145605,HotelBeds,15780037-15,QUA.H6,QUADRUPLE Accessible,"Quadruple Room, Accessible",Quadruple Accessible,"[Quadruple, Accessible, Quadruple Accessible]",2,Accessible,Quadruple,None,Quadruple,4.0,4.0,102,-1.0,"Bed size cannot be single, if it accommadate f..."
3,15780037,145605,HotelBeds,15780037-16,ROO.RO,Room RUN OF HOUSE,Run Of House,Room Run Of House,"[Room, Run, Of, House, Room Run, Run Of, Of Ho...",1,Room Run Of House,,None,,NaN,1.0,103,NaN,NaN
4,15780037,145605,HotelBeds,15780037-17,SUI.ST,SUITE STANDARD,Suite,Suite Standard,"[Suite, Standard, Suite Standard]",1,Suite Standard,,King,Suite,NaN,2.0,104,0.0,suites normaly with king/queen/double/twon bed...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,38751099,13046,HotelBeds,38751099-60,SUI.SU,SUITE SUPERIOR,Suite Superior,Suite Superior,"[Suite, Superior, Suite Superior]",1,Suite Superior,,King,Suite,NaN,2.0,495,0,-same-
396,38751099,13046,HotelBeds,38751099-60,SUI.2D-SU,SUITE SUPERIOR 2 DOUBLE BEDS,Suite Superior,Suite Superior 2 Double Beds,"[Suite, Superior, 2, Double, Beds, Suite Super...",2,Suite Superior 2 Beds,Double,Double,Suite,2.0,4.0,496,0,-same-
397,38751099,13046,HotelBeds,38751099-61,SUI.B1,1-Bedroom Suite,"Suite, 1 Bedroom",1 Bedroom Suite,"[1, Bedroom, Suite, 1 Bedroom, Bedroom Suite, ...",1,1 Bedroom Suite,,King,Suite,NaN,2.0,497,0,does the sweet have a bedroom
398,38751099,13046,HotelBeds,38751099-61,SUI.B1-3,SUITE 1 BEDROOM,"Suite, 1 Bedroom",Suite 1 Bedroom,"[Suite, 1, Bedroom, Suite 1, 1 Bedroom, Suite ...",1,Suite 1 Bedroom,,King,Suite,NaN,2.0,498,0,suite have a bedroom
399,38751099,13046,HotelBeds,38751099-61,SUI.B1-KG,SUITE KING BED 1 BEDROOM,"Suite, 1 Bedroom",Suite Bed 1 Bedroom,"[Suite, King, Bed, 1, Bedroom, Suite King, Kin...",1,Suite King Bed 1 Bedroom,,King,Suite,NaN,2.0,499,0,-same-

In [219]:
merged_df = merged_df.drop(['SupplierHotelId','SupplierName','GroupId' ,'HotelBeds RoomCode','room_type','Vervotech MappedStandardName', 'room_type_1','room_style_1','no_of_person','Unnamed: 0'], axis=1)

In [220]:
merged_df

,Vervotech ID,HotelBeds RoomName,ngrams,bed_count,bed_size,room_style,no_of_people,Label,Remarks
0,15780037,"Premier Skyline View Room, 2 Queen Beds","[Premier, Skyline, View, Room,, 2, Queen, Beds...",2,Queen,Premier,4.0,-1.0,2 queen bed can accommodate 4 people
1,15780037,"Premier Skyline View Room, King Bed","[Premier, Skyline, View, Room,, King, Bed, Pre...",1,King,Premier,2.0,-1.0,no. of people should be 2
2,15780037,QUADRUPLE Accessible,"[Quadruple, Accessible, Quadruple Accessible]",2,None,Quadruple,4.0,-1.0,"Bed size cannot be single, if it accommadate f..."
3,15780037,Room RUN OF HOUSE,"[Room, Run, Of, House, Room Run, Run Of, Of Ho...",1,None,,1.0,NaN,NaN
4,15780037,SUITE STANDARD,"[Suite, Standard, Suite Standard]",1,King,Suite,2.0,0.0,suites normaly with king/queen/double/twon bed...
...,...,...,...,...,...,...,...,...,...
395,38751099,SUITE SUPERIOR,"[Suite, Superior, Suite Superior]",1,King,Suite,2.0,0,-same-
396,38751099,SUITE SUPERIOR 2 DOUBLE BEDS,"[Suite, Superior, 2, Double, Beds, Suite Super...",2,Double,Suite,4.0,0,-same-
397,38751099,1-Bedroom Suite,"[1, Bedroom, Suite, 1 Bedroom, Bedroom Suite, ...",1,King,Suite,2.0,0,does the sweet have a bedroom
398,38751099,SUITE 1 BEDROOM,"[Suite, 1, Bedroom, Suite 1, 1 Bedroom, Suite ...",1,King,Suite,2.0,0,suite have a bedroom
399,38751099,SUITE KING BED 1 BEDROOM,"[Suite, King, Bed, 1, Bedroom, Suite King, Kin...",1,King,Suite,2.0,0,-same-

In [221]:
# df_1 = merged_df[['Vervotech ID','room_type','ngrams','bed_count','bed_size','room_style','Vevotech Naming','hotelRoomType','no_of_people','Label','Remarks']]

In [222]:
df_1 = merged_df

In [223]:
df_1.tail(3)

,Vervotech ID,HotelBeds RoomName,ngrams,bed_count,bed_size,room_style,no_of_people,Label,Remarks
397,38751099,1-Bedroom Suite,"[1, Bedroom, Suite, 1 Bedroom, Bedroom Suite, ...",1,King,Suite,2.0,0,does the sweet have a bedroom
398,38751099,SUITE 1 BEDROOM,"[Suite, 1, Bedroom, Suite 1, 1 Bedroom, Suite ...",1,King,Suite,2.0,0,suite have a bedroom
399,38751099,SUITE KING BED 1 BEDROOM,"[Suite, King, Bed, 1, Bedroom, Suite King, Kin...",1,King,Suite,2.0,0,-same-

In [224]:
df1 = df_1.iloc[0:100]
df2 = df_1.iloc[100:200]
df3 = df_1.iloc[200:300]
df4 = df_1.iloc[300:400]

In [233]:
df1

,Vervotech ID,HotelBeds RoomName,ngrams,bed_count,bed_size,room_style,no_of_people,Label,Remarks
0,15780037,"Premier Skyline View Room, 2 Queen Beds","[Premier, Skyline, View, Room,, 2, Queen, Beds...",2,Queen,Premier,4.0,-1.0,2 queen bed can accommodate 4 people
1,15780037,"Premier Skyline View Room, King Bed","[Premier, Skyline, View, Room,, King, Bed, Pre...",1,King,Premier,2.0,-1.0,no. of people should be 2
2,15780037,QUADRUPLE Accessible,"[Quadruple, Accessible, Quadruple Accessible]",2,None,Quadruple,4.0,-1.0,"Bed size cannot be single, if it accommadate f..."
3,15780037,Room RUN OF HOUSE,"[Room, Run, Of, House, Room Run, Run Of, Of Ho...",1,None,,1.0,NaN,NaN
4,15780037,SUITE STANDARD,"[Suite, Standard, Suite Standard]",1,King,Suite,2.0,0.0,suites normaly with king/queen/double/twon bed...
...,...,...,...,...,...,...,...,...,...
95,15614808,1 King Studio Mobility Access Roll In Shower,"[1, King, Studio, Mobility, Access, Roll, In, ...",1,King,Studio,2.0,-1.0,no. of people should be 2
96,15614808,SUITE Accessible-2 Queen Beds,"[Suite, Accessible, 2, Queen, Beds, Suite Acce...",2,Queen,Suite,4.0,NaN,NaN
97,15614808,SUITE Accessible KING SIZE BED,"[Suite, Accessible, King, Size, Bed, Suite Acc...",1,King,Suite,2.0,-1.0,no. of people should be 2
98,15253183,DOUBLE DELUXE KING BED,"[Double, Deluxe, King, Bed, Double Deluxe, Del...",1,King,Deluxe,2.0,NaN,NaN
99,15253183,DOUBLE QUEEN SIZE BED,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Queen,Double,2.0,NaN,NaN

In [229]:
df1.to_csv("Niranjani_test_set_Level_2.csv")
df2.to_csv("Nileka_test_set_Level_2.csv")
df3.to_csv("saumya_test_set_Level_2.csv")
df4.to_csv("Nuwan_test_set_Level_2.csv")
#df5.to_csv("YungChing_test_set_Level_2.csv")

## Type A

In [103]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [105]:

style_size_dict = {
    'Deluxe': 'King',
    'Corner': 'Queen',
    'Standard': 'Single',
    'Suit': 'Twin Beds'
    
}

def extract_style_size(row):
    room_type = row['hotelRoomType']
    room_style = row['room_style']
    bed_size = row['bed_size']
    
    if not room_style and not bed_size:
        for token in nlp(room_type):
            if token.text in style_size_dict:
                bed_size = style_size_dict[token.text]
                room_style = token.text
                break
    
    elif not room_style:
        for token in nlp(room_type):
            if token.text in style_size_dict:
                room_style = token.text
                break
                
    elif not bed_size:
        if room_style in style_size_dict:
            bed_size = style_size_dict[room_style]
    
    row['room_style'] = room_style
    row['bed_size'] = bed_size
    return row

df = df.apply(extract_style_size, axis=1)

In [114]:
df.head(20)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,bed_size,room_style,Vevotech Naming,hotelRoomType
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier King Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,King,Apartment,Apartment Premier,Apartment Premier King Bed
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 King Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,King,Apartment,Apartment,Apartment 2 King Beds
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment King Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,King,Apartment,Apartment,Apartment King Size Bed
3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Queen Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",2,Queen,,Queen Room,Queen Size Bed
4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite King Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,King,Suite,Suite,Suite King Size Bed
5,15324900,141230,HotelBeds,15324900-1,DBL.2Q-DX,2 Queen Beds Deluxe Nonsmoke,"Deluxe, 2 Queen",2 Queen Beds Deluxe Nonsmoke,"[2, Queen, Beds, Deluxe, Nonsmoke, 2 Queen, Qu...",2,Queen,Deluxe,"Deluxe, 2 Queen",2 Queen Beds Deluxe Nonsmoke
6,15324900,141230,HotelBeds,15324900-1,ROO.2Q-DX,2 QUEEN BEDS DELUXE NONSMOKE,"Deluxe, 2 Queen",2 Queen Beds Deluxe Nonsmoke,"[2, Queen, Beds, Deluxe, Nonsmoke, 2 Queen, Qu...",2,Queen,Deluxe,"Deluxe, 2 Queen",2 Queen Beds Deluxe Nonsmoke
7,15324900,141230,HotelBeds,15324900-2,DBL.DX-KG,King Deluxe Accessible Roll Shwr Nosmk,"Deluxe, King, Accessible",King Deluxe Accessible Roll Shwr Nosmk,"[King, Deluxe, Accessible, Roll, Shwr, Nosmk, ...",1,King,Deluxe,"Deluxe, King, Accessible",King Deluxe Accessible Roll Shwr Nosmk
8,15324900,141230,HotelBeds,15324900-3,DBL.KG,KING LEISURE NONSMOKE,King Room,King Leisure Nonsmoke,"[King, Leisure, Nonsmoke, King Leisure, Leisur...",1,King,Leisure,King Room,King Leisure Nonsmoke
9,15324900,141230,HotelBeds,15324900-4,DBL.H6-KG,DOUBLE Accessible KING SIZE BED,"King Room, Accessible",Accessible King Size Bed,"[Double, Accessible, King, Size, Bed, Double A...",2,King,Accessible,"King Room, Accessible",Accessible King Size Bed
10,15324900,141230,HotelBeds,15324900-5,DBL.CV-KG,DOUBLE CITY VIEW KING BED,"King Room, City View",City View King Bed,"[Double, City, View, King, Bed, Double City, C...",2,King,,"King Room, City View",City View King Bed
11,15324900,141230,HotelBeds,15324900-6,QUA.2Q-NM,QUADRUPLE 2 QUEEN BEDS NON SMOKING,Quadruple Room,Quadruple 2 Queen Beds Non Smoking,"[Quadruple, 2, Queen, Beds, Non, Smoking, Quad...",2,Queen,,Quadruple Room,Quadruple 2 Queen Beds Non Smoking
12,15324900,141230,HotelBeds,15324900-7,DBL.NM-QN,1 QUEEN BED NONSMOKING,Queen Room,1 Queen Bed Nonsmoking,"[1, Queen, Bed, Nonsmoking, 1 Queen, Queen Bed...",1,Queen,,Queen Room,1 Queen Bed Nonsmoking
13,15324900,141230,HotelBeds,15324900-7,ROO.NM-QN,Room QUEEN BED NON SMOKING,Queen Room,Room Queen Bed Non Smoking,"[Room, Queen, Bed, Non, Smoking, Room Queen, Q...",1,Queen,,Queen Room,Room Queen Bed Non Smoking
14,15324900,141230,HotelBeds,15324900-7,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Queen Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",2,Queen,,Queen Room,Queen Size Bed
15,15324900,141230,HotelBeds,15324900-8,DBT.2Q,Double or Twin 2 QUEEN BEDS,Room - 2 Queen,Or Twin 2 Queen Beds,"[Double, Or, Twin, 2, Queen, Beds, Double Or, ...",2,Twin,,Room - 2 Queen,Or Twin 2 Queen Beds
16,15324900,141230,HotelBeds,15324900-8,DBL.2Q,DOUBLE 2 QUEEN BEDS,Room - 2 Queen,2 Queen Beds,"[Double, 2, Queen, Beds, Double 2, 2 Queen, Qu...",2,Queen,,Room - 2 Queen,2 Queen Beds
17,15324900,141230,HotelBeds,15324900-9,DBL.H6-2Q,DOUBLE Accessible-2 Queen Beds,"Room - 2 Queen, Accessible",Accessible 2 Queen Beds,"[Double, Accessible, 2, Queen, Beds, Double Ac...",2,Queen,Accessible,"Room - 2 Queen, Accessible",Accessible 2 Queen Beds
18,15324900,141230,HotelBeds,15324900-10,ROO.RO,Room RUN OF HOUSE,Run Of House,Room Run Of House,"[Room, Run, Of, House, Room Run, Run Of, Of Ho...",1,,,Run Of House,Room Run Of House
19,15324900,141230,HotelBeds,15324900-11,DBL.ST-2,DOUBLE STANDARD,Standard Room,Standard,"[Double, Standard, Double Standard]",2,,Standard,Standard Room,Standard

## Type B

In [ ]:
room_bed_dict = {
    "Standard": "King",
    "Deluxe": "Queen",
    "Suite": "King",
    "Executive": "King"
    
    # add more pairs
}

In [ ]:
for i, row in df.iterrows():
    if row['bed_size'] == '':
        room_style = row['room_style']
        if room_style in room_bed_dict:
            bed_size = room_bed_dict[room_style]
            df.at[i, 'bed_size'] = bed_size

In [ ]:
df.to_csv("test_3.csv")