In [1]:
import pandas as pd
import numpy as np
import gensim

In [2]:
# Load the pre-trained word2vec model
model_path = 'GoogleNews-vectors-negative300.bin'
model = gensim.models.KeyedVectors.load_word2vec_format(model_path, binary=True)

In [3]:
# Define the list of words for bed sizes
# bed_size_key_words = ['Twin',  
#     'Queen', 
#     'King' ,
#     'California King',
#     'Twin XL' ,
#     'Full' ,
#     'Single' ,
#     'Sofa' ,
#     'Rollaway' ,
#     'Bunk' ,
#     'Murphy' ,
#     'Trundle' ,
#     'Daybed',
#     'Crib' , 'Pack' 
#     ,'Air Mattress', 
#     'Twin Beds', 
#     'Double Bed', 
#     'Queen Beds',
#     'Double Bed', 
#     'Queen Bed',                  
#     'King Beds' ,
#     'California King Beds',
#     'Twin XL Beds' ,
#     'Full Beds' ,
#     'Single Beds' ,
#     'Sofa Beds' ,
#     'Rollaway Beds' ,
#     'Bunk Beds' ,
#     'Murphy Beds' ,
#     'Trundle Beds' ,
#     'Daybed Beds',
#         'Crib Beds' , 'Pack Beds'                  
#  ]



# room_style_key_words = [
#     'Queen',
#     'Apartment',
#     'Standard',
#     'Suite',
#     'Deluxe',
#     'Double',
#     'Executive',
#     'Leisure',
#     'Club',
#     'Superior',
#     'Connecting',
#     'Accessible',
#     'Family',
#     'Pet-Friendly',
#     'Jacuzzi',
#     'Adjoining',
#     'Loft',
#     'Penthouse Suite',
#     'Standard Room',
#     'Suite Room',
#     'Deluxe Room',
#     'Executive Room',
#     'Club Room',
#     'Superior Room',
#     'Connecting Room',
#     'Accessible Room',
#     'Family Room',
#     'Pet-Friendly Room',
#     'Jacuzzi Room',
#     'Adjoining Room',
#     'Loft Room',
#     'Penthouse Suite Room'
    
# ]

In [4]:
bed_size_key_words = [ 
    'Queen', 
    'Queens'
    'King' ,
    'King Size'
    'California King',
    'Twin XL' ,
    'Full' ,
    'Single' ,
    'Twin', 
    'Sofa' ,
    'Rollaway' ,
    'Bunk' ,
    'Murphy' ,
    'Trundle' ,
    'Premium',
    'Daybed',
    'Crib' , 'Pack' 
    ,'Air Mattress', 
    'Twin Beds'

 ]



room_style_key_words = [
    'Standard',
    'Deluxe',
    'Joint',
    'Connecting',
    'Superior'
    'Studio'
    'Suite',
    'Apartment',
    'Premier',
    'Executive',
    'Dormitory',
    'Cabana',
    'Club',
    'Villa',
    'Penthouse',
    'Leisure'
]

In [56]:
df = pd.read_csv("Vevotec_Sample Data Room mapping- Hotelbeds_1.csv")

In [6]:
# df = pd.read_csv("merged.csv")
# df = df.head(100)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1957 entries, 0 to 1956
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Vervotech ID                  1957 non-null   int64
 1   SupplierHotelId               1957 non-null   int64
 2   SupplierName                  1957 non-null   object
 3   GroupId                       1957 non-null   object
 4   HotelBeds RoomCode            1957 non-null   object
 5   HotelBeds RoomName            1957 non-null   object
 6   Vervotech MappedStandardName  1957 non-null   object
dtypes: int64(2), object(5)
memory usage: 107.1+ KB

In [8]:
df['room_type'] = df['HotelBeds RoomName']

In [9]:
replacements = {"Two": "2", "Three": "3", "1":" 1 ", "2":" 2 ", "3":" 3 ", "-":" " ,"/":" / " }

# replace values in the 'room_type' column using the dictionary
df['room_type'] = df['room_type'].replace(replacements, regex=True)

In [10]:
df['room_type'] = df['room_type'].str.title()

In [11]:
df.head(4)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier King Bed
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 King Beds
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment King Size Bed
3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Queen Size Bed

In [12]:
df['room_type'] = df['room_type'].astype(str)

In [13]:
# Replace occurrences of "digit space digit" with "digitdigit"
df['room_type'] = df['room_type'].str.replace(r'(\d) (\d)', r'\1\2')

/tmp/ipykernel_6718/4128053049.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['room_type'] = df['room_type'].str.replace(r'(\d) (\d)', r'\1\2')

In [15]:
# Define a function to tokenize the room types and extract bigrams and trigrams
# def get_ngrams(room_type):
#     tokens = room_type.split()
#     bigrams = [' '.join(tokens[i:i+2]) for i in range(len(tokens)-1)]
#     trigrams = [' '.join(tokens[i:i+3]) for i in range(len(tokens)-2)]
#     return tokens + bigrams + trigrams

import re

def get_ngrams(room_type):
    # Replace occurrences of "digit space digit" with "digitdigit"
    #room_type = room_type.replace(r'(\d) (\d)', r'\1\2')
    room_type = re.sub(r'(\d) (\d)', r'\1\2', room_type)
    
    tokens = room_type.split()
    bigrams = [' '.join(tokens[i:i+2]) for i in range(len(tokens)-1)]
    trigrams = [' '.join(tokens[i:i+3]) for i in range(len(tokens)-2)]
    return tokens + bigrams + trigrams

df['room_type'] = df['room_type'].astype(str)
# Apply the get_ngrams function to the room types column
df['ngrams'] = df['room_type'].apply(get_ngrams)

In [16]:
df['ngrams'][0]

['Apartment',
 'Premier',
 'King',
 'Bed',
 'Apartment Premier',
 'Premier King',
 'King Bed',
 'Apartment Premier King',
 'Premier King Bed']

In [17]:
df['ngrams'][0]

['Apartment',
 'Premier',
 'King',
 'Bed',
 'Apartment Premier',
 'Premier King',
 'King Bed',
 'Apartment Premier King',
 'Premier King Bed']

In [18]:
import spacy

nlp = spacy.load("en_core_web_sm")


def get_bed_count(trigrams):
    for trigram in trigrams:
        if "Bed" in trigram or "Beds" in trigram or "bed" in trigram or "beds" in trigram:
            doc = nlp(trigram)
            for token in doc:
                if token.is_digit:
                    return int(token.text)
    return 1

df["bed_count"] = df["ngrams"].apply(get_bed_count)

2023-04-28 11:27:15.291946: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-28 11:27:22.707381: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-04-28 11:27:22.707656: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-04-28 11:27:22.707685: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-04-28 11:27:27.834904: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-04-28 11:27:27.834935: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-04-28 11:27:27.834953: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ushan-Inspiron-5558): /proc/driver/nvidia/version does not exist

In [19]:
df['room_type_1'] = df['room_type']

In [20]:
df['ngrams_1'] = df['room_type_1'].apply(get_ngrams)

In [21]:
df.tail(2)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,ngrams_1
1955,41268569,907505,HotelBeds,41268569-14,SUI.B1-KG,1 KING BED 1 BEDROOM SUITE,"Suite, 1 Bedroom",1 King Bed 1 Bedroom Suite,"[1, King, Bed, 1, Bedroom, Suite, 1 King, King...",1,1 King Bed 1 Bedroom Suite,"[1, King, Bed, 1, Bedroom, Suite, 1 King, King..."
1956,41268569,907505,HotelBeds,41268569-15,SUI.KG,1 KING BED 1 BEDROOM SUITE WITH BALCONY,"Suite, 1 Bedroom, Balcony",1 King Bed 1 Bedroom Suite With Balcony,"[1, King, Bed, 1, Bedroom, Suite, With, Balcon...",1,1 King Bed 1 Bedroom Suite With Balcony,"[1, King, Bed, 1, Bedroom, Suite, With, Balcon..."

In [22]:
import re

# loop through the rows of the dataframe
for index, row in df.iterrows():
    room_type = row['room_type']
    
    # extract the room style and bed size
    room_style = ''
    bed_size = ''
    
    if 'Double' in room_type:
        room_style = 'Double'
        bed_size = room_type.replace('Double', '').strip()
    elif 'Triple' in room_type:
        room_style = 'Triple'
        bed_size = room_type.replace('Triple', '').strip()
    elif 'Quadruple' in room_type:
        room_style = 'Quadruple'
        bed_size = room_type.replace('Quadruple', '').strip()
    else:
        room_style = ''
        bed_size = room_type
        
    
    # update the row with the new information
    df.at[index, 'room_style_1'] = room_style
    df.at[index, 'room_type_1'] = bed_size

In [23]:
df['ngrams'][0]

['Apartment',
 'Premier',
 'King',
 'Bed',
 'Apartment Premier',
 'Premier King',
 'King Bed',
 'Apartment Premier King',
 'Premier King Bed']

In [24]:
bed_size_key_words

['Queen',
 'QueensKing',
 'King SizeCalifornia King',
 'Twin XL',
 'Full',
 'Single',
 'Twin',
 'Sofa',
 'Rollaway',
 'Bunk',
 'Murphy',
 'Trundle',
 'Premium',
 'Daybed',
 'Crib',
 'Pack',
 'Air Mattress',
 'Twin Beds']

In [25]:
import pandas as pd
import re

# Define a regular expression to match trigrams that end with "bed" or "beds"
#regex = re.compile(r'\b\w+\s+\w+\s+(beds?|sofa bed)\b')
#regex = re.compile(r'\b\w+\s+(?:twin|full|queen|king)\b')
regex = re.compile(r'\b\w+\s+\w+\s+(Bed|Beds)\b')

# Define a function to find the best matching bed size keyword for a given ngram
def get_best_match(ngram):
    matches = []
    for bed_size in bed_size_key_words:
        if bed_size in ngram:
            matches.append(bed_size)
    if len(matches) == 0:
        return None
    elif len(matches) == 1:
        return matches[0]
    else:
        # If there are multiple matches, return the longest match
        return max(matches, key=len)

#Find the best matching bed size keyword for each ngram and add it to a new column
df['bed_size'] = df['ngrams'].apply(lambda x: get_best_match(x))
df['bed_size_1'] = df['ngrams_1'].apply(lambda x: get_best_match(x))


#df['bed_size'] = df['ngrams'].apply(lambda x: [get_best_match(ngram) for ngram in x if regex.search(ngram)] if x else None)



# def find_bed_size(ngrams):
#     for ngram in ngrams:
#         if re.search(r'\b\w+\s+beds?\b', ngram):
#             for word in bed_size_key_words:
#                 if any(w in ngram.lower() for w in word.split()):
#                     return word.capitalize()
#     return None

# df['bed_size'] = df['ngrams'].apply(find_bed_size)

In [26]:
df.head(100)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,ngrams_1,room_style_1,bed_size,bed_size_1
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier King Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier King Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",,None,None
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 King Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 King Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",,None,None
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment King Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,Apartment King Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",,None,None
3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Queen Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Queen Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",Double,Queen,Queen
4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite King Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,Suite King Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,15780037,145605,HotelBeds,15780037-9,DBL.EY,DOUBLE ECONOMY,Economy,Double Economy,"[Double, Economy, Double Economy]",1,Economy,"[Double, Economy, Double Economy]",Double,None,None
96,15780037,145605,HotelBeds,15780037-10,DBL.KG,DOUBLE KING SIZE BED,King Room,Double King Size Bed,"[Double, King, Size, Bed, Double King, King Si...",1,King Size Bed,"[Double, King, Size, Bed, Double King, King Si...",Double,None,None
97,15780037,145605,HotelBeds,15780037-11,SUI.LO,SUITE LOFT,Loft Suite,Suite Loft,"[Suite, Loft, Suite Loft]",1,Suite Loft,"[Suite, Loft, Suite Loft]",,None,None
98,15780037,145605,HotelBeds,15780037-12,ROO.PE,Room PREMIER,Premier,Room Premier,"[Room, Premier, Room Premier]",1,Room Premier,"[Room, Premier, Room Premier]",,None,None
99,15780037,145605,HotelBeds,15780037-12,DBL.PE-5,DOUBLE PREMIER,Premier,Double Premier,"[Double, Premier, Double Premier]",1,Premier,"[Double, Premier, Double Premier]",Double,None,None

In [27]:
num_null = df['bed_size'].isnull().sum()
num_null

1535

In [28]:

# Loop through each row of the DataFrame
for index, row in df.iterrows():
    bed_size = row['bed_size']
    room_type = row['room_type']
    
    # Check if the bed_size is not None
    if bed_size is not None:
        # Remove the bed_size keyword from the room_type string
        room_type = room_type.replace(bed_size, '').strip()
        room_type = room_type.replace('beds', '').strip()
        
        # Update the room_type column in the DataFrame
        df.at[index, 'room_type'] = room_type

In [29]:
df.head(2)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,ngrams_1,room_style_1,bed_size,bed_size_1
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier King Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier King Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",,None,None
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 King Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 King Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",,None,None

In [30]:

# Define a function to find the best matching key word for a list of ngrams
def get_best_match(ngrams, key_words):
    best_match = ''
    best_similarity = -1
    for ngram in ngrams:
        if ngram in model:
            for key_word in key_words:
                # Split key word into individual words
                key_word_tokens = key_word.split()
                # Check if all words in key word are present in ngram
                if all(token in ngram.split() for token in key_word_tokens):
                    similarity = model.similarity(ngram, key_word)
                    if similarity > best_similarity:
                        best_similarity = similarity
                        best_match = key_word
    return best_match



# Apply the get_best_match function to the ngrams column for bed sizes
#df['bed_size'] = df['ngrams'].apply(lambda x: get_best_match(x, bed_size_key_words))

# Apply the get_best_match function to the ngrams column for room styles
df['room_style'] = df['ngrams'].apply(lambda x: get_best_match(x, room_style_key_words))

In [32]:
df.head(403)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,ngrams_1,room_style_1,bed_size,bed_size_1,room_style
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier King Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier King Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",,None,None,Apartment
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 King Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 King Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",,None,None,Apartment
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment King Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,Apartment King Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",,None,None,Apartment
3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Queen Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",Double,Queen,Queen,
4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite King Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,Suite King Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",,None,None,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,38380068,589938,HotelBeds,38380068-7,DBL.KG,1 KNG BED LEISURE NONSMOKING,King Room,1 Kng Bed Leisure Nonsmoking,"[1, Kng, Bed, Leisure, Nonsmoking, 1 Kng, Kng ...",1,1 Kng Bed Leisure Nonsmoking,"[1, Kng, Bed, Leisure, Nonsmoking, 1 Kng, Kng ...",,None,None,Leisure
399,38380068,589938,HotelBeds,38380068-7,DBL.KG-8,DOUBLE KING SIZE BED,King Room,Double King Size Bed,"[Double, King, Size, Bed, Double King, King Si...",1,King Size Bed,"[Double, King, Size, Bed, Double King, King Si...",Double,None,None,
400,38380068,589938,HotelBeds,38380068-7,DBL.KG-NM,DOUBLE KING BED NON SMOKING,King Room,Double King Bed Non Smoking,"[Double, King, Bed, Non, Smoking, Double King,...",1,King Bed Non Smoking,"[Double, King, Bed, Non, Smoking, Double King,...",Double,None,None,
401,38380068,589938,HotelBeds,38380068-8,DBL.H6-KG,DOUBLE Accessible KING SIZE BED,"King Room, Accessible",Double Accessible King Size Bed,"[Double, Accessible, King, Size, Bed, Double A...",1,Accessible King Size Bed,"[Double, Accessible, King, Size, Bed, Double A...",Double,None,None,
402,38380068,589938,HotelBeds,38380068-8,ROO.H6-KG,Room Accessible KING SIZE BED,"King Room, Accessible",Room Accessible King Size Bed,"[Room, Accessible, King, Size, Bed, Room Acces...",1,Room Accessible King Size Bed,"[Room, Accessible, King, Size, Bed, Room Acces...",,None,None,

In [42]:
#df['room_type_1'] = df['room_type']

In [43]:
# df['Vevotech Naming'] = df['Vervotech MappedStandardName']
# df['hotelRoomType'] = df['room_type']

In [44]:
df.head(100)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,ngrams_1,room_style_1,bed_size,bed_size_1,room_style
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier King Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier King Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",,None,None,Apartment
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 King Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 King Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",,None,None,Apartment
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment King Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,Apartment King Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",,None,None,Apartment
3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Queen Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",Double,Queen,Queen,
4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite King Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,Suite King Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",,None,None,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,15780037,145605,HotelBeds,15780037-9,DBL.EY,DOUBLE ECONOMY,Economy,Double Economy,"[Double, Economy, Double Economy]",1,Economy,"[Double, Economy, Double Economy]",Double,None,None,
96,15780037,145605,HotelBeds,15780037-10,DBL.KG,DOUBLE KING SIZE BED,King Room,Double King Size Bed,"[Double, King, Size, Bed, Double King, King Si...",1,King Size Bed,"[Double, King, Size, Bed, Double King, King Si...",Double,None,None,
97,15780037,145605,HotelBeds,15780037-11,SUI.LO,SUITE LOFT,Loft Suite,Suite Loft,"[Suite, Loft, Suite Loft]",1,Suite Loft,"[Suite, Loft, Suite Loft]",,None,None,
98,15780037,145605,HotelBeds,15780037-12,ROO.PE,Room PREMIER,Premier,Room Premier,"[Room, Premier, Room Premier]",1,Room Premier,"[Room, Premier, Room Premier]",,None,None,Premier
99,15780037,145605,HotelBeds,15780037-12,DBL.PE-5,DOUBLE PREMIER,Premier,Double Premier,"[Double, Premier, Double Premier]",1,Premier,"[Double, Premier, Double Premier]",Double,None,None,Premier

In [129]:
# fill empty values in the "bed_type" column with corresponding values in "bed_type_1"
#df['room_style'] = df.apply(lambda x: x['room_style_1'] if x['room_style'] == '' else x['room_style'], axis=1)

In [130]:
df.head(5)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier King Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier King Bed,,None,Apartment
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 King Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 King Beds,,None,Apartment
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment King Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,Apartment King Size Bed,,None,Apartment
3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Queen Size Bed,Double,Queen,
4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite King Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,Suite King Size Bed,,None,

In [131]:

# add a new column "no_of_person" with values from "bed_count" column
#df['no_of_person'] = df['bed_count']

df.loc[df['room_style_1'] == 'Double', 'no_of_person'] = 2
df.loc[df['room_style_1'] == 'Triple', 'no_of_person'] = 3
df.loc[df['room_style_1'] == 'Quadruple', 'no_of_person'] = 4

In [132]:
# update the no_of_people column where room_style is king, queen or premium
df.loc[df['bed_size'].isin(['King', 'Queen', 'premium','Premium',  'Full', 'Sofa', 'Bunk']), 'no_of_people'] = df['bed_count'] * 2

# update the no_of_people column for other room_style values
df.loc[~df['bed_size'].isin(['King', 'Queen', 'premium','Premium',  'Full', 'Sofa', 'Bunk']), 'no_of_people'] = df['bed_count'] * 1

In [133]:
df.head(15)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier King Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier King Bed,,None,Apartment,NaN,1.0
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 King Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 King Beds,,None,Apartment,NaN,2.0
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment King Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,Apartment King Size Bed,,None,Apartment,NaN,1.0
3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Queen Size Bed,Double,Queen,,2.0,2.0
4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite King Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,Suite King Size Bed,,None,,NaN,1.0
5,15324900,141230,HotelBeds,15324900-1,DBL.2Q-DX,2 Queen Beds Deluxe Nonsmoke,"Deluxe, 2 Queen",2 Beds Deluxe Nonsmoke,"[2, Queen, Beds, Deluxe, Nonsmoke, 2 Queen, Qu...",2,2 Queen Beds Deluxe Nonsmoke,,Queen,Deluxe,NaN,4.0
6,15324900,141230,HotelBeds,15324900-1,ROO.2Q-DX,2 QUEEN BEDS DELUXE NONSMOKE,"Deluxe, 2 Queen",2 Beds Deluxe Nonsmoke,"[2, Queen, Beds, Deluxe, Nonsmoke, 2 Queen, Qu...",2,2 Queen Beds Deluxe Nonsmoke,,Queen,Deluxe,NaN,4.0
7,15324900,141230,HotelBeds,15324900-2,DBL.DX-KG,King Deluxe Accessible Roll Shwr Nosmk,"Deluxe, King, Accessible",King Deluxe Accessible Roll Shwr Nosmk,"[King, Deluxe, Accessible, Roll, Shwr, Nosmk, ...",1,King Deluxe Accessible Roll Shwr Nosmk,,None,Deluxe,NaN,1.0
8,15324900,141230,HotelBeds,15324900-3,DBL.KG,KING LEISURE NONSMOKE,King Room,King Leisure Nonsmoke,"[King, Leisure, Nonsmoke, King Leisure, Leisur...",1,King Leisure Nonsmoke,,None,Leisure,NaN,1.0
9,15324900,141230,HotelBeds,15324900-4,DBL.H6-KG,DOUBLE Accessible KING SIZE BED,"King Room, Accessible",Double Accessible King Size Bed,"[Double, Accessible, King, Size, Bed, Double A...",1,Accessible King Size Bed,Double,None,,2.0,1.0
10,15324900,141230,HotelBeds,15324900-5,DBL.CV-KG,DOUBLE CITY VIEW KING BED,"King Room, City View",Double City View King Bed,"[Double, City, View, King, Bed, Double City, C...",1,City View King Bed,Double,None,,2.0,1.0
11,15324900,141230,HotelBeds,15324900-6,QUA.2Q-NM,QUADRUPLE 2 QUEEN BEDS NON SMOKING,Quadruple Room,Quadruple 2 Beds Non Smoking,"[Quadruple, 2, Queen, Beds, Non, Smoking, Quad...",2,2 Queen Beds Non Smoking,Quadruple,Queen,,4.0,4.0
12,15324900,141230,HotelBeds,15324900-7,DBL.NM-QN,1 QUEEN BED NONSMOKING,Queen Room,1 Bed Nonsmoking,"[1, Queen, Bed, Nonsmoking, 1 Queen, Queen Bed...",1,1 Queen Bed Nonsmoking,,Queen,,NaN,2.0
13,15324900,141230,HotelBeds,15324900-7,ROO.NM-QN,Room QUEEN BED NON SMOKING,Queen Room,Room Bed Non Smoking,"[Room, Queen, Bed, Non, Smoking, Room Queen, Q...",1,Room Queen Bed Non Smoking,,Queen,,NaN,2.0
14,15324900,141230,HotelBeds,15324900-7,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Queen Size Bed,Double,Queen,,2.0,2.0

In [134]:
df['bed_size'].unique()

array([None, 'Queen', 'Premium', 'Twin', 'Single', 'Full', 'Bunk', 'Sofa'],
      dtype=object)

In [135]:
# replace blank values in room_style column with room_style_1 values
df.loc[df['room_style'] == '', 'room_style'] = df.loc[df['room_style'] == '', 'room_style_1']

In [136]:
# find the maximum value between no_of_person and no_of_people columns
df['no_of_people'] = df[['no_of_person', 'no_of_people']].max(axis=1)

In [137]:
# replace bed_count with 2 where no_of_people is 4 and bed_count is 1
df.loc[(df['no_of_people'] == 4) & (df['bed_count'] == 1), 'bed_count'] = 2

In [ ]:
df.loc[( df["room_style"].isin(["delux", "Club", "Suite"])) & (booking_df["bed_size"].isnull()), "bed_size"] = "Queen"

In [163]:
df['room_style'].unique()

array(['Apartment', 'Double', '', 'Deluxe', 'Leisure', 'Quadruple',
       'Standard', 'Executive', 'Triple', 'Premier', 'Club', 'Dormitory',
       'Villa', 'Penthouse'], dtype=object)

In [164]:
df['ngrams'][402]

['Room',
 'Accessible',
 'King',
 'Size',
 'Bed',
 'Room Accessible',
 'Accessible King',
 'King Size',
 'Size Bed',
 'Room Accessible King',
 'Accessible King Size',
 'King Size Bed']

In [138]:
df.head(406)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier King Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier King Bed,,None,Apartment,NaN,1.0
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 King Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 King Beds,,None,Apartment,NaN,2.0
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment King Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,Apartment King Size Bed,,None,Apartment,NaN,1.0
3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Queen Size Bed,Double,Queen,Double,2.0,2.0
4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite King Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,Suite King Size Bed,,None,,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,38380068,589938,HotelBeds,38380068-8,DBL.H6-KG,DOUBLE Accessible KING SIZE BED,"King Room, Accessible",Double Accessible King Size Bed,"[Double, Accessible, King, Size, Bed, Double A...",1,Accessible King Size Bed,Double,None,Double,2.0,2.0
402,38380068,589938,HotelBeds,38380068-8,ROO.H6-KG,Room Accessible KING SIZE BED,"King Room, Accessible",Room Accessible King Size Bed,"[Room, Accessible, King, Size, Bed, Room Acces...",1,Room Accessible King Size Bed,,None,,NaN,1.0
403,38380068,589938,HotelBeds,38380068-9,ROO.ST,STANDARD ROOM,King/Queen Room,Standard Room,"[Standard, Room, Standard Room]",1,Standard Room,,None,Standard,NaN,1.0
404,38380068,589938,HotelBeds,38380068-10,TWN.KG-8,TWIN KING SIZE BED,King/Twin Room,King Size Bed,"[Twin, King, Size, Bed, Twin King, King Size, ...",1,Twin King Size Bed,,Twin,,NaN,1.0
405,38380068,589938,HotelBeds,38380068-11,DBL.KG-PI,DOUBLE PREMIUM KING BED,"Premium, King",Double King Bed,"[Double, Premium, King, Bed, Double Premium, P...",1,Premium King Bed,Double,Premium,Double,2.0,2.0

In [139]:
df1 = df[df['room_style_1'] == 'Quadruple']
df1.head(100)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
11,15324900,141230,HotelBeds,15324900-6,QUA.2Q-NM,QUADRUPLE 2 QUEEN BEDS NON SMOKING,Quadruple Room,Quadruple 2 Beds Non Smoking,"[Quadruple, 2, Queen, Beds, Non, Smoking, Quad...",2,2 Queen Beds Non Smoking,Quadruple,Queen,Quadruple,4.0,4.0
25,15333170,276800,HotelBeds,15333170-2,QUA.2Q-DX,QUADRUPLE DELUXE 2 QUEEN BEDS,"Deluxe, Quadruple",Quadruple Deluxe 2 Beds,"[Quadruple, Deluxe, 2, Queen, Beds, Quadruple ...",2,Deluxe 2 Queen Beds,Quadruple,Queen,Deluxe,4.0,4.0
54,15471297,45947,HotelBeds,15471297-14,QUA.H6,QUADRUPLE Accessible,"Quadruple Room, Accessible",Quadruple Accessible,"[Quadruple, Accessible, Quadruple Accessible]",2,Accessible,Quadruple,None,Quadruple,4.0,4.0
92,15780037,145605,HotelBeds,15780037-6,QUA.CV-DX,QUADRUPLE DELUXE CITY VIEW,"Deluxe, Quadruple, City View",Quadruple Deluxe City View,"[Quadruple, Deluxe, City, View, Quadruple Delu...",2,Deluxe City View,Quadruple,None,Deluxe,4.0,4.0
102,15780037,145605,HotelBeds,15780037-15,QUA.H6,QUADRUPLE Accessible,"Quadruple Room, Accessible",Quadruple Accessible,"[Quadruple, Accessible, Quadruple Accessible]",2,Accessible,Quadruple,None,Quadruple,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1793,39793169,618128,HotelBeds,39793169-3,QUA.2Q-NM,QUADRUPLE 2 QUEEN BEDS NON SMOKING,Quadruple Room,Quadruple 2 Beds Non Smoking,"[Quadruple, 2, Queen, Beds, Non, Smoking, Quad...",2,2 Queen Beds Non Smoking,Quadruple,Queen,Quadruple,4.0,4.0
1810,39972811,749281,HotelBeds,39972811-12,QUA.2Q-DX,QUADRUPLE DELUXE 2 QUEEN BEDS,"Deluxe, Quadruple",Quadruple Deluxe 2 Beds,"[Quadruple, Deluxe, 2, Queen, Beds, Quadruple ...",2,Deluxe 2 Queen Beds,Quadruple,Queen,Deluxe,4.0,4.0
1819,39972811,749281,HotelBeds,39972811-21,QUA.PE-5,QUADRUPLE PREMIER,"Premier, Quadruple",Quadruple Premier,"[Quadruple, Premier, Quadruple Premier]",2,Premier,Quadruple,None,Premier,4.0,4.0
1853,40050192,13432,HotelBeds,40050192-4,QUA.CB-EJ,QUADRUPLE CLUB EXECUTIVE,"Club Executive, Quadruple",Quadruple Club Executive,"[Quadruple, Club, Executive, Quadruple Club, C...",2,Club Executive,Quadruple,None,Club,4.0,4.0
1865,40050192,13432,HotelBeds,40050192-12,QUA.DX,QUADRUPLE DELUXE,"Deluxe, Quadruple",Quadruple Deluxe,"[Quadruple, Deluxe, Quadruple Deluxe]",2,Deluxe,Quadruple,None,Deluxe,4.0,4.0

In [140]:
df.head(50)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier King Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier King Bed,,None,Apartment,NaN,1.0
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 King Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 King Beds,,None,Apartment,NaN,2.0
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment King Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,Apartment King Size Bed,,None,Apartment,NaN,1.0
3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Queen Size Bed,Double,Queen,Double,2.0,2.0
4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite King Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,Suite King Size Bed,,None,,NaN,1.0
5,15324900,141230,HotelBeds,15324900-1,DBL.2Q-DX,2 Queen Beds Deluxe Nonsmoke,"Deluxe, 2 Queen",2 Beds Deluxe Nonsmoke,"[2, Queen, Beds, Deluxe, Nonsmoke, 2 Queen, Qu...",2,2 Queen Beds Deluxe Nonsmoke,,Queen,Deluxe,NaN,4.0
6,15324900,141230,HotelBeds,15324900-1,ROO.2Q-DX,2 QUEEN BEDS DELUXE NONSMOKE,"Deluxe, 2 Queen",2 Beds Deluxe Nonsmoke,"[2, Queen, Beds, Deluxe, Nonsmoke, 2 Queen, Qu...",2,2 Queen Beds Deluxe Nonsmoke,,Queen,Deluxe,NaN,4.0
7,15324900,141230,HotelBeds,15324900-2,DBL.DX-KG,King Deluxe Accessible Roll Shwr Nosmk,"Deluxe, King, Accessible",King Deluxe Accessible Roll Shwr Nosmk,"[King, Deluxe, Accessible, Roll, Shwr, Nosmk, ...",1,King Deluxe Accessible Roll Shwr Nosmk,,None,Deluxe,NaN,1.0
8,15324900,141230,HotelBeds,15324900-3,DBL.KG,KING LEISURE NONSMOKE,King Room,King Leisure Nonsmoke,"[King, Leisure, Nonsmoke, King Leisure, Leisur...",1,King Leisure Nonsmoke,,None,Leisure,NaN,1.0
9,15324900,141230,HotelBeds,15324900-4,DBL.H6-KG,DOUBLE Accessible KING SIZE BED,"King Room, Accessible",Double Accessible King Size Bed,"[Double, Accessible, King, Size, Bed, Double A...",1,Accessible King Size Bed,Double,None,Double,2.0,2.0
10,15324900,141230,HotelBeds,15324900-5,DBL.CV-KG,DOUBLE CITY VIEW KING BED,"King Room, City View",Double City View King Bed,"[Double, City, View, King, Bed, Double City, C...",1,City View King Bed,Double,None,Double,2.0,2.0
11,15324900,141230,HotelBeds,15324900-6,QUA.2Q-NM,QUADRUPLE 2 QUEEN BEDS NON SMOKING,Quadruple Room,Quadruple 2 Beds Non Smoking,"[Quadruple, 2, Queen, Beds, Non, Smoking, Quad...",2,2 Queen Beds Non Smoking,Quadruple,Queen,Quadruple,4.0,4.0
12,15324900,141230,HotelBeds,15324900-7,DBL.NM-QN,1 QUEEN BED NONSMOKING,Queen Room,1 Bed Nonsmoking,"[1, Queen, Bed, Nonsmoking, 1 Queen, Queen Bed...",1,1 Queen Bed Nonsmoking,,Queen,,NaN,2.0
13,15324900,141230,HotelBeds,15324900-7,ROO.NM-QN,Room QUEEN BED NON SMOKING,Queen Room,Room Bed Non Smoking,"[Room, Queen, Bed, Non, Smoking, Room Queen, Q...",1,Room Queen Bed Non Smoking,,Queen,,NaN,2.0
14,15324900,141230,HotelBeds,15324900-7,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Queen Size Bed,Double,Queen,Double,2.0,2.0
15,15324900,141230,HotelBeds,15324900-8,DBT.2Q,Double or Twin 2 QUEEN BEDS,Room - 2 Queen,Double Or Twin 2 Beds,"[Double, Or, Twin, 2, Queen, Beds, Double Or, ...",2,Or Twin 2 Queen Beds,Double,Queen,Double,2.0,4.0
16,15324900,141230,HotelBeds,15324900-8,DBL.2Q,DOUBLE 2 QUEEN BEDS,Room - 2 Queen,Double 2 Beds,"[Double, 2, Queen, Beds, Double 2, 2 Queen, Qu...",2,2 Queen Beds,Double,Queen,Double,2.0,4.0
17,15324900,141230,HotelBeds,15324900-9,DBL.H6-2Q,DOUBLE Accessible-2 Queen Beds,"Room - 2 Queen, Accessible",Double Accessible 2 Beds,"[Double, Accessible, 2, Queen, Beds, Double Ac...",2,Accessible 2 Queen Beds,Double,Queen,Double,2.0,4.0
18,15324900,141230,HotelBeds,15324900-10,ROO.RO,Room RUN OF HOUSE,Run Of House,Room Run Of House,"[Room, Run, Of, House, Room Run, Run Of, Of Ho...",1,Room Run Of House,,None,,NaN,1.0
19,15324900,141230,HotelBeds,15324900-11,DBL.ST-2,DOUBLE STANDARD,Standard Room,Double Standard,"[Double, Standard, Double Standard]",1,Standard,Double,None,Standard,2.0,2.0
20,15324900,141230,HotelBeds,15324900-11,ROO.ST-11,Room STANDARD,Standard Room,Room Standard,"[Room, Standard, Room Standard]",1,Room Standard,,None,Standard,NaN,1.0
21,15324900,141230,HotelBeds,15324900-11,ROO.ST,STANDARD ROOM,Standard Room,Standard Room,"[Standard, Room, Standard Room]",1,Standard Room,,None,Standard,NaN,1.0
22,15324900,141230,HotelBeds,15324900-12,SUI.NM,KING BED & LIVING ROOM SUITE NONSMOKING,Suite,King Bed & Living Room Suite Nonsmoking,"[King, Bed, &, Living, Room, Suite, Nonsmoking...",1,King Bed & Living Room Suite Nonsmoking,,None,,NaN,1.0
23,15324900,141230,HotelBeds,15324900-13,SUI.B1-KG,SUITE KING BED 1 BEDROOM,"Suite, 1 Bedroom",Suite King Bed 1 Bedroom,"[Suite, King, Bed, 1, Bedroom, Suite King, Kin...",1,Suite King Bed 1 Bedroom,,None,,NaN,1.0
24,15333170,276800,HotelBeds,15333170-1,DBL.DX-KG,DOUBLE DELUXE KING BED,"Deluxe, King",Double Deluxe King Bed,"[Double, Deluxe, King, Bed, Double Deluxe, Del...",1,Deluxe King Bed,Double,None,Deluxe,2.0,2.0
25,15333170,276800,HotelBeds,15333170-2,QUA.2Q-DX,QUADRUPLE DELUXE 2 QUEEN BEDS,"Deluxe, Quadruple",Quadruple Deluxe 2 Beds,"[Quadruple, Deluxe, 2, Queen, Beds, Quadruple ...",2,Deluxe 2 Queen Beds,Quadruple,Queen,Deluxe,4.0,4.0
26,15333170,276800,HotelBeds,15333170-3,DBL.DX-QN,DOUBLE DELUXE QUEEN BED,"Deluxe, Queen",Double Deluxe Bed,"[Double, Deluxe, Queen, Bed, Double Deluxe, De...",1,Deluxe Queen Bed,Double,Queen,Deluxe,2.0,2.0
27,15333170,276800,HotelBeds,15333170-4,DBL.KG,DOUBLE KING SIZE BED,King Room,Double King Size Bed,"[Double, King, Size, Bed, Double King, King Si...",1,King Size Bed,Double,None,Double,2.0,2.0
28,15333170,276800,HotelBeds,15333170-5,DBL.LX,DOUBLE LUXURY,Luxury,Double Luxury,"[Double, Luxury, Double Luxury]",1,Luxury,Double,None,Double,2.0,2.0
29,15333170,276800,HotelBeds,15333170-6,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Queen Size Bed,Double,Queen,Double,2.0,2.0
30,15471297,45947,HotelBeds,15471297-1,DBL.H6,DOUBLE Accessible,Accessible Room,Double Accessible,"[Double, Accessible, Double Accessible]",1,Accessible,Double,None,Double,2.0,2.0
31,15471297,45947,HotelBeds,15471297-2,DBL.2Q-1,2 Queen Beds Corner,"Corner, 2 Queen",2 Beds Corner,"[2, Queen, Beds, Corner, 2 Queen, Queen Beds, ...",2,2 Queen Beds Corner,,Queen,,NaN,4.0
32,15471297,45947,HotelBeds,15471297-3,ROO.KG-NM,1 King Bed Corner,"Corner, King",1 King Bed Corner,"[1, King, Bed, Corner, 1 King, King Bed, Bed C...",1,1 King Bed Corner,,None,,NaN,1.0
33,15471297,45947,HotelBeds,15471297-4,ROO.EJ,Room EXECUTIVE,Executive,Room Executive,"[Room, Executive, Room Executive]",1,Room Executive,,None,Executive,NaN,1.0
34,15471297,45947,HotelBeds,15471297-4,DBL.EJ-1,DOUBLE EXECUTIVE,Executive,Double Executive,"[Double, Executive, Double Executive]",1,Executive,Double,None,Executive,2.0,2.0
35,15471297,45947,HotelBeds,15471297-5,SUI.EJ-KG,Executive Suite,Executive Suite,Executive Suite,"[Executive, Suite, Executive Suite]",1,Executive Suite,,None,Executive,NaN,1.0
36,15471297,45947,HotelBeds,15471297-5,SUI.2D-EJ,SUITE EXECUTIVE 2 DOUBLE BEDS,Executive Suite,Suite Executive 2 Double Beds,"[Suite, Executive, 2, Double, Beds, Suite Exec...",2,Suite Executive 2 Beds,Double,None,Executive,2.0,2.0
37,15471297,45947,HotelBeds,15471297-5,SUI.EJ-5,SUITE EXECUTIVE,Executive Suite,Suite Executive,"[Suite, Executive, Suite Executive]",1,Suite Executive,,None,Executive,NaN,1.0
38,15471297,45947,HotelBeds,15471297-6,DBL.EJ-KG,Executive Terrace,"Executive, King, Terrace",Executive Terrace,"[Executive, Terrace, Executive Terrace]",1,Executive Terrace,,None,Executive,NaN,1.0
39,15471297,45947,HotelBeds,15471297-7,JSU.ST,JUNIOR SUITE STANDARD,Junior Suite,Junior Suite Standard,"[Junior, Suite, Standard, Junior Suite, Suite ...",1,Junior Suite Standard,,None,Standard,NaN,1.0
40,15471297,45947,HotelBeds,15471297-7,JSU.S9,JUNIOR SUITE Private external bathroom,Junior Suite,Junior Suite Private External Bathroom,"[Junior, Suite, Private, External, Bathroom, J...",1,Junior Suite Private External Bathroom,,None,,NaN,1.0
41,15471297,45947,HotelBeds,15471297-7,JSU.KG-8,JUNIOR SUITE KING SIZE BED,Junior Suite,Junior Suite King Size Bed,"[Junior, Suite, King, Size, Bed, Junior Suite,...",1,Junior Suite King Size Bed,,None,,NaN,1.0
42,15471297,45947,HotelBeds,15471297-7,JSU.KG,Junior Suite,Junior Suite,Junior Suite,"[Junior, Suite, Junior Suite]",1,Junior Suite,,None,,NaN,1.0
43,15471297,45947,HotelBeds,15471297-8,ROO.KG,Room KING SIZE BED,King Room,Room King Size Bed,"[Room, King, Size, Bed, Room King, King Size, ...",1,Room King Size Bed,,None,,NaN,1.0
44,15471297,45947,HotelBeds,15471297-8,DBL.KG,DOUBLE KING SIZE BED,King Room,Double King Size Bed,"[Double, King, Size, Bed, Double King, King Si...",1,King Size Bed,Double,None,Double,2.0,2.0
45,15471297,45947,HotelBeds,15471297-8,DBL.KG-NM,1 King Bed,King Room,1 King Bed,"[1, King, Bed, 1 King, King Bed, 1 King Bed]",1,1 King Bed,,None,,NaN,1.0
46,15471297,45947,HotelBeds,15471297-9,DBL.CV-KG,DOUBLE CITY VIEW KING BED,"King Room, City View",Double City View King Bed,"[Double, City, View, King, Bed, Double City, C...",1,City View King Bed,Double,None,Double,2.0,2.0
47,15471297,45947,HotelBeds,15471297-9,ROO.CV-KG,1 King Bed with City View,"King Room, City View",1 King Bed With City View,"[1, King, Bed, With, City, View, 1 King, King ...",1,1 King Bed With City View,,None,,NaN,1.0
48,15471297,45947,HotelBeds,15471297-10,DBL.KG-PI,DOUBLE PREMIUM KING BED,"Premium, King",Double King Bed,"[Double, Premium, King, Bed, Double Premium, P...",1,Premium King Bed,Double,Premium,Double,2.0,2.0
49,15471297,45947,HotelBeds,15471297-10,SGL.KG-PI,SINGLE PREMIUM KING BED,"Premium, King",Single King Bed,"[Single, Premium, King, Bed, Single Premium, P...",1,Single Premium King Bed,,Premium,,NaN,2.0

In [141]:
df1 = df[df['bed_count']== 0]
df1

Empty DataFrame
Columns: [Vervotech ID, SupplierHotelId, SupplierName, GroupId, HotelBeds RoomCode, HotelBeds RoomName, Vervotech MappedStandardName, room_type, ngrams, bed_count, room_type_1, room_style_1, bed_size, room_style, no_of_person, no_of_people]
Index: []

In [142]:
#df = df[~df['bed_count'].isin([1003, 1406])]

In [143]:
# group by bed_count, bed_size, room_style and get the count of records
grouped = df.groupby(['bed_count', 'bed_size', 'room_style','no_of_people']).size().reset_index(name='count')

grouped

    bed_count bed_size room_style  no_of_people  count
0           1     Bunk                      2.0      1
1           1     Bunk     Double           2.0      1
2           1     Full                      2.0      5
3           1     Full     Deluxe           2.0      3
4           1     Full  Executive           2.0      1
5           1  Premium                      2.0     37
6           1  Premium     Deluxe           2.0      1
7           1  Premium     Double           2.0     19
8           1  Premium     Triple           3.0      1
9           1    Queen                      2.0     62
10          1    Queen  Apartment           2.0      1
11          1    Queen       Club           2.0      1
12          1    Queen     Deluxe           2.0      8
13          1    Queen     Double           2.0     45
14          1    Queen  Executive           2.0      4
15          1    Queen    Premier           2.0      1
16          1    Queen   Standard           2.0      4
17          1    Queen     Triple           3.0      1
18          1   Single                      1.0     13
19          1   Single       Club           1.0      2
20          1   Single     Deluxe           1.0      3
21          1   Single     Deluxe           2.0      2
22          1   Single     Double           2.0      1
23          1   Single  Executive           1.0      1
24          1   Single   Standard           1.0      5
25          1     Sofa                      2.0      8
26          1     Twin                      1.0      2
27          1     Twin     Deluxe           2.0      4
28          1     Twin     Double           2.0     15
29          1     Twin   Standard           1.0      5
30          1     Twin   Standard           2.0      9
31          2  Premium                      4.0      4
32          2  Premium  Apartment           4.0      1
33          2  Premium     Double           4.0      1
34          2  Premium  Quadruple           4.0      1
35          2    Queen                      4.0     45
36          2    Queen  Apartment           4.0      1
37          2    Queen       Club           4.0      2
38          2    Queen     Deluxe           4.0     10
39          2    Queen     Double           4.0     36
40          2    Queen  Executive           4.0      3
41          2    Queen    Premier           4.0      7
42          2    Queen  Quadruple           4.0     21
43          2    Queen     Triple           4.0      1
44          2     Sofa                      4.0      1
45          2     Twin                      2.0      1
46          2     Twin     Deluxe           2.0      4
47          2     Twin     Double           2.0     16
48          2     Twin  Executive           2.0      1

In [144]:
grouped.head(50)

    bed_count bed_size room_style  no_of_people  count
0           1     Bunk                      2.0      1
1           1     Bunk     Double           2.0      1
2           1     Full                      2.0      5
3           1     Full     Deluxe           2.0      3
4           1     Full  Executive           2.0      1
5           1  Premium                      2.0     37
6           1  Premium     Deluxe           2.0      1
7           1  Premium     Double           2.0     19
8           1  Premium     Triple           3.0      1
9           1    Queen                      2.0     62
10          1    Queen  Apartment           2.0      1
11          1    Queen       Club           2.0      1
12          1    Queen     Deluxe           2.0      8
13          1    Queen     Double           2.0     45
14          1    Queen  Executive           2.0      4
15          1    Queen    Premier           2.0      1
16          1    Queen   Standard           2.0      4
17          1    Queen     Triple           3.0      1
18          1   Single                      1.0     13
19          1   Single       Club           1.0      2
20          1   Single     Deluxe           1.0      3
21          1   Single     Deluxe           2.0      2
22          1   Single     Double           2.0      1
23          1   Single  Executive           1.0      1
24          1   Single   Standard           1.0      5
25          1     Sofa                      2.0      8
26          1     Twin                      1.0      2
27          1     Twin     Deluxe           2.0      4
28          1     Twin     Double           2.0     15
29          1     Twin   Standard           1.0      5
30          1     Twin   Standard           2.0      9
31          2  Premium                      4.0      4
32          2  Premium  Apartment           4.0      1
33          2  Premium     Double           4.0      1
34          2  Premium  Quadruple           4.0      1
35          2    Queen                      4.0     45
36          2    Queen  Apartment           4.0      1
37          2    Queen       Club           4.0      2
38          2    Queen     Deluxe           4.0     10
39          2    Queen     Double           4.0     36
40          2    Queen  Executive           4.0      3
41          2    Queen    Premier           4.0      7
42          2    Queen  Quadruple           4.0     21
43          2    Queen     Triple           4.0      1
44          2     Sofa                      4.0      1
45          2     Twin                      2.0      1
46          2     Twin     Deluxe           2.0      4
47          2     Twin     Double           2.0     16
48          2     Twin  Executive           2.0      1

In [145]:
df.head(5)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier King Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier King Bed,,None,Apartment,NaN,1.0
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 King Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 King Beds,,None,Apartment,NaN,2.0
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment King Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,Apartment King Size Bed,,None,Apartment,NaN,1.0
3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Queen Size Bed,Double,Queen,Double,2.0,2.0
4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite King Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,Suite King Size Bed,,None,,NaN,1.0

In [146]:
df1 = df[df['bed_size']== "Trundle"]
df1

Empty DataFrame
Columns: [Vervotech ID, SupplierHotelId, SupplierName, GroupId, HotelBeds RoomCode, HotelBeds RoomName, Vervotech MappedStandardName, room_type, ngrams, bed_count, room_type_1, room_style_1, bed_size, room_style, no_of_person, no_of_people]
Index: []

In [147]:
df1 = df[df['bed_size']=="Bunk"]
df1

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
281,15474166,13045,HotelBeds,15474166-13,SUI.BK,Freedom Trail Suite - 1 King & Bunk Beds,"Freedom Trail Suite, Bunk Bed",Freedom Trail Suite 1 King & Beds,"[Freedom, Trail, Suite, 1, King, &, Bunk, Beds...",1,Freedom Trail Suite 1 King & Bunk Beds,,Bunk,,NaN,2.0
665,39454042,815811,HotelBeds,39454042-3,DBL.BK,DOUBLE BUNK BED,"Double Room, Bunk Bed",Double Bed,"[Double, Bunk, Bed, Double Bunk, Bunk Bed, Dou...",1,Bunk Bed,Double,Bunk,Double,2.0,2.0

In [148]:
#grouped.to_csv("grouped_summary.csv")

In [149]:
null_rows = df[df["bed_size"].isnull()]
null_rows

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier King Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier King Bed,,None,Apartment,NaN,1.0
1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 King Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 King Beds,,None,Apartment,NaN,2.0
2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment King Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,Apartment King Size Bed,,None,Apartment,NaN,1.0
4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite King Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,Suite King Size Bed,,None,,NaN,1.0
7,15324900,141230,HotelBeds,15324900-2,DBL.DX-KG,King Deluxe Accessible Roll Shwr Nosmk,"Deluxe, King, Accessible",King Deluxe Accessible Roll Shwr Nosmk,"[King, Deluxe, Accessible, Roll, Shwr, Nosmk, ...",1,King Deluxe Accessible Roll Shwr Nosmk,,None,Deluxe,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1941,41268569,907505,HotelBeds,41268569-5,DBL.CV-KG,1 KING BED CITY VIEW ROOM,"King Room, City View",1 King Bed City View Room,"[1, King, Bed, City, View, Room, 1 King, King ...",1,1 King Bed City View Room,,None,,NaN,1.0
1950,41268569,907505,HotelBeds,41268569-11,TWN.H6-1,2 QN MOBILITY ACCESSIBLE W/ ROLL IN SHOWER,"Room - 2 Queen, Accessible",2 Qn Mobility Accessible W / Roll In Shower,"[2, Qn, Mobility, Accessible, W, /, Roll, In, ...",1,2 Qn Mobility Accessible W / Roll In Shower,,None,,NaN,1.0
1954,41268569,907505,HotelBeds,41268569-13,ROO.CV,1 BED ROOM CITY VIEW WITH BALCONY,"Room With City View, Balcony",1 Bed Room City View With Balcony,"[1, Bed, Room, City, View, With, Balcony, 1 Be...",1,1 Bed Room City View With Balcony,,None,,NaN,1.0
1955,41268569,907505,HotelBeds,41268569-14,SUI.B1-KG,1 KING BED 1 BEDROOM SUITE,"Suite, 1 Bedroom",1 King Bed 1 Bedroom Suite,"[1, King, Bed, 1, Bedroom, Suite, 1 King, King...",1,1 King Bed 1 Bedroom Suite,,None,,NaN,1.0
1956,41268569,907505,HotelBeds,41268569-15,SUI.KG,1 KING BED 1 BEDROOM SUITE WITH BALCONY,"Suite, 1 Bedroom, Balcony",1 King Bed 1 Bedroom Suite With Balcony,"[1, King, Bed, 1, Bedroom, Suite, With, Balcon...",1,1 King Bed 1 Bedroom Suite With Balcony,,None,,NaN,1.0

In [150]:
# null_counts = null_values.sum()
# null_counts

In [151]:
grouped.head(50)

    bed_count bed_size room_style  no_of_people  count
0           1     Bunk                      2.0      1
1           1     Bunk     Double           2.0      1
2           1     Full                      2.0      5
3           1     Full     Deluxe           2.0      3
4           1     Full  Executive           2.0      1
5           1  Premium                      2.0     37
6           1  Premium     Deluxe           2.0      1
7           1  Premium     Double           2.0     19
8           1  Premium     Triple           3.0      1
9           1    Queen                      2.0     62
10          1    Queen  Apartment           2.0      1
11          1    Queen       Club           2.0      1
12          1    Queen     Deluxe           2.0      8
13          1    Queen     Double           2.0     45
14          1    Queen  Executive           2.0      4
15          1    Queen    Premier           2.0      1
16          1    Queen   Standard           2.0      4
17          1    Queen     Triple           3.0      1
18          1   Single                      1.0     13
19          1   Single       Club           1.0      2
20          1   Single     Deluxe           1.0      3
21          1   Single     Deluxe           2.0      2
22          1   Single     Double           2.0      1
23          1   Single  Executive           1.0      1
24          1   Single   Standard           1.0      5
25          1     Sofa                      2.0      8
26          1     Twin                      1.0      2
27          1     Twin     Deluxe           2.0      4
28          1     Twin     Double           2.0     15
29          1     Twin   Standard           1.0      5
30          1     Twin   Standard           2.0      9
31          2  Premium                      4.0      4
32          2  Premium  Apartment           4.0      1
33          2  Premium     Double           4.0      1
34          2  Premium  Quadruple           4.0      1
35          2    Queen                      4.0     45
36          2    Queen  Apartment           4.0      1
37          2    Queen       Club           4.0      2
38          2    Queen     Deluxe           4.0     10
39          2    Queen     Double           4.0     36
40          2    Queen  Executive           4.0      3
41          2    Queen    Premier           4.0      7
42          2    Queen  Quadruple           4.0     21
43          2    Queen     Triple           4.0      1
44          2     Sofa                      4.0      1
45          2     Twin                      2.0      1
46          2     Twin     Deluxe           2.0      4
47          2     Twin     Double           2.0     16
48          2     Twin  Executive           2.0      1

In [152]:

df1 = df[(df['bed_size']== 'Murphy')]
df1

Empty DataFrame
Columns: [Vervotech ID, SupplierHotelId, SupplierName, GroupId, HotelBeds RoomCode, HotelBeds RoomName, Vervotech MappedStandardName, room_type, ngrams, bed_count, room_type_1, room_style_1, bed_size, room_style, no_of_person, no_of_people]
Index: []

In [153]:
df1 = df[(df['room_style']== 'Suite') & (df['bed_size']=='Single')]
df1

Empty DataFrame
Columns: [Vervotech ID, SupplierHotelId, SupplierName, GroupId, HotelBeds RoomCode, HotelBeds RoomName, Vervotech MappedStandardName, room_type, ngrams, bed_count, room_type_1, room_style_1, bed_size, room_style, no_of_person, no_of_people]
Index: []

In [154]:
df['room_style_1'][1]

''

In [155]:
empty_values_count = df['room_style'].str.strip().eq('').sum()
empty_values_count

731

In [157]:
# df.loc[df['room_style'] == '', 'room_style'] = 'Standard'
# df.loc[df['bed_size'] == '', 'bed_size'] = 'Single'

In [231]:
#df.to_csv("test_5.csv")

In [158]:
df.head(1)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier King Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier King Bed,,None,Apartment,NaN,1.0

In [161]:
df1 = pd.read_csv("Nileka_test_set.csv")
df2 = pd.read_csv("Niranjani_test_set.csv")
df3 = pd.read_csv("Nuwan_test_set.csv")
df4 = pd.read_csv("saumya_test_set_Updated.csv")

In [162]:

# concatenate the dataframes
merged_df = pd.concat([df1, df2, df3, df4], axis=0, ignore_index=True)

In [93]:
merged_df = merged_df.drop(['Unnamed: 11','Unnamed: 9','Unnamed: 10'], axis=1)

In [94]:
merged_df

,Unnamed: 0,room_type,ngrams,bed_count,bed_size,room_style,Vevotech Naming,hotelRoomType,no_of_person,Label,Remarks
0,200,Double Accessible,"['Double', 'Accessible', 'Double Accessible']",1,Single,Double,Accessible Room,Double Accessible,2,1,NaN
1,201,Room Accessible,"['Room', 'Accessible', 'Room Accessible']",1,Single,Standard,Accessible Room,Room Accessible,1,1,NaN
2,202,Room Club,"['Room', 'Club', 'Room Club']",1,Single,Standard,Club,Room Club,1,-1,Club rooms have more benefits than standard rooms
3,203,Double Club,"['Double', 'Club', 'Double Club']",1,Single,Double,Club,Double Club,2,-1,Club rooms have more benefits than double rooms
4,204,Double Club King Bed,"['Double', 'Club', 'King', 'Bed', 'Double Club...",1,King,Double,Club,Double Club King Bed,2,-1,Club rooms have more benefits than double rooms
...,...,...,...,...,...,...,...,...,...,...,...
395,395,Double Executive 2 Double Beds,"['Double', 'Executive', '2', 'Double', 'Beds',...",2,Single,Double,"Executive, 2 Double",Double Executive 2 Double Beds,2,0.0,NaN
396,396,1 King Bed Executive Nonsmoking,"['1', 'King', 'Bed', 'Executive', 'Nonsmoking'...",1,King,Standard,"Executive, King",1 King Bed Executive Nonsmoking,1,-1.0,no. of ppl should be 2
397,397,Quadruple Executive 2 Double Beds,"['Quadruple', 'Executive', '2', 'Double', 'Bed...",2,Single,Double,"Executive, Quadruple",Quadruple Executive 2 Double Beds,2,-1.0,2 Quadruple can accommodate 4 ppl
398,398,1 Kng Bed Leisure Nonsmoking,"['1', 'Kng', 'Bed', 'Leisure', 'Nonsmoking', '...",1,Single,Leisure,King Room,1 Kng Bed Leisure Nonsmoking,1,-1.0,no. of ppl should be 2
399,399,Double King Size Bed,"['Double', 'King', 'Size', 'Bed', 'Double King...",1,King,Double,King Room,Double King Size Bed,2,0.0,NaN

In [96]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       400 non-null    int64
 1   room_type        400 non-null    object
 2   ngrams           400 non-null    object
 3   bed_count        400 non-null    object
 4   bed_size         400 non-null    object
 5   room_style       400 non-null    object
 6   Vevotech Naming  400 non-null    object
 7   hotelRoomType    400 non-null    object
 8   no_of_person     400 non-null    object
 9   Label            356 non-null    object
 10  Remarks          236 non-null    object
dtypes: int64(1), object(10)
memory usage: 34.5+ KB

In [97]:
# Merge the dataframes
merged_df_1 = pd.merge(df, merged_df[['Unnamed: 0', 'Label','Remarks']], left_index=True, right_on='Unnamed: 0')

In [98]:
merged_df_1

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people,Unnamed: 0,Label,Remarks
100,15780037,145605,HotelBeds,15780037-13,DBL.PE,"Premier Skyline View Room, 2 Queen Beds","Premier, 2 Queen, Skyline View","Premier Skyline View Room, 2 Beds","[Premier, Skyline, View, Room,, 2, Queen, Beds...",2,"Premier Skyline View Room, 2 Queen Beds",,Queen,Premier,NaN,4.0,100,-1.0,2 queen bed can accommodate 4 people
101,15780037,145605,HotelBeds,15780037-14,DBL.KG-PE,"Premier Skyline View Room, King Bed","Premier, King, Skyline View","Premier Skyline View Room, Bed","[Premier, Skyline, View, Room,, King, Bed, Pre...",1,"Premier Skyline View Room, King Bed",,King,Premier,NaN,2.0,101,-1.0,no. of people should be 2
102,15780037,145605,HotelBeds,15780037-15,QUA.H6,QUADRUPLE Accessible,"Quadruple Room, Accessible",Quadruple Accessible,"[Quadruple, Accessible, Quadruple Accessible]",2,Accessible,Quadruple,None,Quadruple,4.0,4.0,102,-1.0,"Bed size cannot be single, if it accommadate f..."
103,15780037,145605,HotelBeds,15780037-16,ROO.RO,Room RUN OF HOUSE,Run Of House,Room Run Of House,"[Room, Run, Of, House, Room Run, Run Of, Of Ho...",1,Room Run Of House,,None,,NaN,1.0,103,NaN,NaN
104,15780037,145605,HotelBeds,15780037-17,SUI.ST,SUITE STANDARD,Suite,Suite Standard,"[Suite, Standard, Suite Standard]",1,Suite Standard,,None,Suite,NaN,1.0,104,0.0,suites normaly with king/queen/double/twon bed...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,38751099,13046,HotelBeds,38751099-60,SUI.SU,SUITE SUPERIOR,Suite Superior,Suite Superior,"[Suite, Superior, Suite Superior]",1,Suite Superior,,None,Suite,NaN,1.0,495,0,-same-
296,38751099,13046,HotelBeds,38751099-60,SUI.2D-SU,SUITE SUPERIOR 2 DOUBLE BEDS,Suite Superior,Suite Superior 2 Double Beds,"[Suite, Superior, 2, Double, Beds, Suite Super...",2,Suite Superior 2 Beds,Double,None,Suite,2.0,2.0,496,0,-same-
297,38751099,13046,HotelBeds,38751099-61,SUI.B1,1-Bedroom Suite,"Suite, 1 Bedroom",1 Bedroom Suite,"[1, Bedroom, Suite, 1 Bedroom, Bedroom Suite, ...",1,1 Bedroom Suite,,None,Suite,NaN,1.0,497,0,does the sweet have a bedroom
298,38751099,13046,HotelBeds,38751099-61,SUI.B1-3,SUITE 1 BEDROOM,"Suite, 1 Bedroom",Suite 1 Bedroom,"[Suite, 1, Bedroom, Suite 1, 1 Bedroom, Suite ...",1,Suite 1 Bedroom,,None,Suite,NaN,1.0,498,0,suite have a bedroom
299,38751099,13046,HotelBeds,38751099-61,SUI.B1-KG,SUITE KING BED 1 BEDROOM,"Suite, 1 Bedroom",Suite Bed 1 Bedroom,"[Suite, King, Bed, 1, Bedroom, Suite King, Kin...",1,Suite King Bed 1 Bedroom,,King,Suite,NaN,2.0,499,0,-same-

In [99]:
merged_df_1.to_csv("merged_1.csv")

In [76]:
df1.head()

,Unnamed: 0,room_type,ngrams,bed_count,bed_size,room_style,Vevotech Naming,hotelRoomType,no_of_person,Label,Remarks
0,200,Double Accessible,"['Double', 'Accessible', 'Double Accessible']",1,Single,Double,Accessible Room,Double Accessible,2,1,NaN
1,201,Room Accessible,"['Room', 'Accessible', 'Room Accessible']",1,Single,Standard,Accessible Room,Room Accessible,1,1,NaN
2,202,Room Club,"['Room', 'Club', 'Room Club']",1,Single,Standard,Club,Room Club,1,-1,Club rooms have more benefits than standard rooms
3,203,Double Club,"['Double', 'Club', 'Double Club']",1,Single,Double,Club,Double Club,2,-1,Club rooms have more benefits than double rooms
4,204,Double Club King Bed,"['Double', 'Club', 'King', 'Bed', 'Double Club...",1,King,Double,Club,Double Club King Bed,2,-1,Club rooms have more benefits than double rooms

In [73]:
merged_df = pd.merge(df, df1, left_index=True, right_on='Unnamed: 0', how='left')

In [77]:
merged_df.head(1)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type_x,ngrams_x,bed_count_x,...,room_type_y,ngrams_y,bed_count_y,bed_size_y,room_style_y,Vevotech Naming,hotelRoomType,no_of_person_y,Label,Remarks
NaN,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Float64Index: 1957 entries, nan to nan
Data columns (total 27 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Vervotech ID                  1957 non-null   int64
 1   SupplierHotelId               1957 non-null   int64
 2   SupplierName                  1957 non-null   object
 3   GroupId                       1957 non-null   object
 4   HotelBeds RoomCode            1957 non-null   object
 5   HotelBeds RoomName            1957 non-null   object
 6   Vervotech MappedStandardName  1957 non-null   object
 7   room_type_x                   1957 non-null   object
 8   ngrams_x                      1957 non-null   object
 9   bed_count_x                   1957 non-null   int64
 10  room_type_1                   1957 non-null   object
 11  room_style_1                  1957 non-null   object
 12  bed_size_x                    935 non-null    object
 13  room_style_x                  1957 non-null   object
 14  no_of_person_x                833 non-null    float64
 15  no_of_people                  1957 non-null   float64
 16  Unnamed: 0                    1957 non-null   int64
 17  room_type_y                   100 non-null    object
 18  ngrams_y                      100 non-null    object
 19  bed_count_y                   100 non-null    float64
 20  bed_size_y                    100 non-null    object
 21  room_style_y                  100 non-null    object
 22  Vevotech Naming               100 non-null    object
 23  hotelRoomType                 100 non-null    object
 24  no_of_person_y                100 non-null    float64
 25  Label                         100 non-null    object
 26  Remarks                       48 non-null     object
dtypes: float64(4), int64(4), object(19)
memory usage: 428.1+ KB

In [ ]:
merged_df = merged_df.rename(columns={'room_type_x': 'room_type', 'ngrams_x','bed_count_x',})

In [82]:
merged_df = merged_df[[ 'Vervotech ID','SupplierHotelId','SupplierName','GroupId','HotelBeds RoomCode','HotelBeds RoomName','Vervotech MappedStandardName','room_type_x','ngrams_x','bed_count_x', 'room_type_1','room_style_1','bed_size_x','room_style_x','no_of_person_x','no_of_people','Label','Remarks']]   
merged_df.head(205)

,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type_x,ngrams_x,bed_count_x,room_type_1,room_style_1,bed_size_x,room_style_x,no_of_person_x,no_of_people,Label,Remarks
NaN,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier Bed,"[Apartment, Premier, King, Bed, Apartment Prem...",1,Apartment Premier King Bed,,King,Apartment,NaN,2.0,NaN,NaN
NaN,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 Beds,"[Apartment, 2, King, Beds, Apartment 2, 2 King...",2,Apartment 2 King Beds,,King,Apartment,NaN,4.0,NaN,NaN
NaN,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment Size Bed,"[Apartment, King, Size, Bed, Apartment King, K...",1,Apartment King Size Bed,,King,Apartment,NaN,2.0,NaN,NaN
NaN,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"[Double, Queen, Size, Bed, Double Queen, Queen...",1,Queen Size Bed,Double,Queen,Double,2.0,2.0,NaN,NaN
NaN,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite Size Bed,"[Suite, King, Size, Bed, Suite King, King Size...",1,Suite King Size Bed,,King,Suite,NaN,2.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0.0,15570173,143736,HotelBeds,15570173-1,DBL.H6,DOUBLE Accessible,Accessible Room,Double Accessible,"[Double, Accessible, Double Accessible]",1,Accessible,Double,None,Double,2.0,2.0,1,NaN
1.0,15570173,143736,HotelBeds,15570173-1,ROO.H6,Room Accessible,Accessible Room,Room Accessible,"[Room, Accessible, Room Accessible]",1,Room Accessible,,None,,NaN,1.0,1,NaN
2.0,15570173,143736,HotelBeds,15570173-2,ROO.CB-1,Room CLUB,Club,Room Club,"[Room, Club, Room Club]",1,Room Club,,None,Club,NaN,1.0,-1,Club rooms have more benefits than standard rooms
3.0,15570173,143736,HotelBeds,15570173-2,DBL.CB,DOUBLE CLUB,Club,Double Club,"[Double, Club, Double Club]",1,Club,Double,None,Club,2.0,2.0,-1,Club rooms have more benefits than double rooms
4.0,15570173,143736,HotelBeds,15570173-2,DBL.CB-KG,DOUBLE CLUB KING BED,Club,Double Club Bed,"[Double, Club, King, Bed, Double Club, Club Ki...",1,Club King Bed,Double,King,Club,2.0,2.0,-1,Club rooms have more benefits than double rooms

In [99]:
from pivottablejs import pivot_ui
pivot_ui(df)

In [58]:
df = pd.read_csv("test_5.csv")

In [54]:
df.head(5)

,Unnamed: 0,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,ngrams,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people
0,0,15111741,782331,HotelBeds,15111741-1,APT.KG-PE,APARTMENT PREMIER KING BED,Apartment Premier,Apartment Premier Bed,"['Apartment', 'Premier', 'King', 'Bed', 'Apart...",1,Apartment Premier King Bed,NaN,King,Apartment,NaN,2.0
1,1,15111788,782334,HotelBeds,15111788-1,APT.2K,APARTMENT 2 KING BEDS,Apartment,Apartment 2 Beds,"['Apartment', '2', 'King', 'Beds', 'Apartment ...",2,Apartment 2 King Beds,NaN,King,Apartment,NaN,4.0
2,2,15131097,782325,HotelBeds,15131097-1,APT.KG,APARTMENT KING SIZE BED,Apartment,Apartment Size Bed,"['Apartment', 'King', 'Size', 'Bed', 'Apartmen...",1,Apartment King Size Bed,NaN,King,Apartment,NaN,2.0
3,3,15294880,766775,HotelBeds,15294880-1,DBL.QN,DOUBLE QUEEN SIZE BED,Queen Room,Double Size Bed,"['Double', 'Queen', 'Size', 'Bed', 'Double Que...",1,Queen Size Bed,Double,Queen,Double,2.0,2.0
4,4,15294880,766775,HotelBeds,15294880-2,SUI.KG-1,SUITE KING SIZE BED,Suite,Suite Size Bed,"['Suite', 'King', 'Size', 'Bed', 'Suite King',...",1,Suite King Size Bed,NaN,King,Suite,NaN,2.0

In [7]:
df_1 = df[['room_type','ngrams','bed_count','bed_size','room_style','Vevotech Naming','hotelRoomType','no_of_person']]

In [9]:
df_1.head(3)

,room_type,ngrams,bed_count,bed_size,room_style,Vevotech Naming,hotelRoomType,no_of_person
0,Apartment Premier King Bed,"['Apartment', 'Premier', 'King', 'Bed', 'Apart...",1,King,Apartment,Apartment Premier,Apartment Premier King Bed,1
1,Apartment 2 King Beds,"['Apartment', '2', 'King', 'Beds', 'Apartment ...",2,King,Apartment,Apartment,Apartment 2 King Beds,2
2,Apartment King Size Bed,"['Apartment', 'King', 'Size', 'Bed', 'Apartmen...",1,King,Apartment,Apartment,Apartment King Size Bed,1

In [10]:

# df1 = df_1.iloc[100:200]
# df2 = df_1.iloc[200:300]
# df3 = df_1.iloc[300:400]
# df4 = df_1.iloc[400:500]
# df5 = df_1.iloc[500:600]
# df5 = df_1.iloc[600:700]

In [14]:
# df1.to_csv("Niranjani_test_set.csv")
# df2.to_csv("Nileka_test_set.csv")
# df3.to_csv("saumya_test_set.csv")
# df4.to_csv("Nuwan_test_set.csv")
# df5.to_csv("YungChing_test_set.csv")

In [45]:
df1 = pd.read_csv("Nileka_test_set.csv")
df2 = pd.read_csv("Niranjani_test_set.csv")
df3 = pd.read_csv("Nuwan_test_set.csv")
df4 = pd.read_csv("saumya_test_set_Updated.csv")

In [47]:
merged_df = pd.concat([df1, df2, df3, df4], axis=0, ignore_index=True)

In [48]:
merged_df = merged_df.drop(['Unnamed: 11','Unnamed: 9','Unnamed: 10'], axis=1)

In [60]:
df1 = merged_df

In [68]:
df1.head()

,Unnamed: 0,room_type,ngrams,bed_count,bed_size,room_style,Vevotech Naming,hotelRoomType,no_of_person,Label,Remarks
0,200,Double Accessible,"['Double', 'Accessible', 'Double Accessible']",1,Single,Double,Accessible Room,Double Accessible,2,1,NaN
1,201,Room Accessible,"['Room', 'Accessible', 'Room Accessible']",1,Single,Standard,Accessible Room,Room Accessible,1,1,NaN
2,202,Room Club,"['Room', 'Club', 'Room Club']",1,Single,Standard,Club,Room Club,1,-1,Club rooms have more benefits than standard rooms
3,203,Double Club,"['Double', 'Club', 'Double Club']",1,Single,Double,Club,Double Club,2,-1,Club rooms have more benefits than double rooms
4,204,Double Club King Bed,"['Double', 'Club', 'King', 'Bed', 'Double Club...",1,King,Double,Club,Double Club King Bed,2,-1,Club rooms have more benefits than double rooms

In [66]:
# Merge the dataframes based on the index of df and the "Unnamed: 0" column of df1
merged_df = pd.merge(df, df1[['Unnamed: 0', 'Label', 'Remarks']], left_index=True, right_on='Unnamed: 0')

In [67]:
merged_df

,Unnamed: 0,Unnamed: 0_x,Vervotech ID,SupplierHotelId,SupplierName,GroupId,HotelBeds RoomCode,HotelBeds RoomName,Vervotech MappedStandardName,room_type,...,bed_count,room_type_1,room_style_1,bed_size,room_style,no_of_person,no_of_people,Unnamed: 0_y,Label,Remarks
100,100,100,15780037,145605,HotelBeds,15780037-13,DBL.PE,"Premier Skyline View Room, 2 Queen Beds","Premier, 2 Queen, Skyline View","Premier Skyline View Room, 2 Beds",...,2,"Premier Skyline View Room, 2 Queen Beds",NaN,Queen,Premier,NaN,4.0,100,-1.0,2 queen bed can accommodate 4 people
101,101,101,15780037,145605,HotelBeds,15780037-14,DBL.KG-PE,"Premier Skyline View Room, King Bed","Premier, King, Skyline View","Premier Skyline View Room, Bed",...,1,"Premier Skyline View Room, King Bed",NaN,King,Premier,NaN,2.0,101,-1.0,no. of people should be 2
102,102,102,15780037,145605,HotelBeds,15780037-15,QUA.H6,QUADRUPLE Accessible,"Quadruple Room, Accessible",Quadruple Accessible,...,2,Accessible,Quadruple,NaN,Quadruple,4.0,4.0,102,-1.0,"Bed size cannot be single, if it accommadate f..."
103,103,103,15780037,145605,HotelBeds,15780037-16,ROO.RO,Room RUN OF HOUSE,Run Of House,Room Run Of House,...,1,Room Run Of House,NaN,NaN,NaN,NaN,1.0,103,NaN,NaN
104,104,104,15780037,145605,HotelBeds,15780037-17,SUI.ST,SUITE STANDARD,Suite,Suite Standard,...,1,Suite Standard,NaN,NaN,Suite,NaN,1.0,104,0.0,suites normaly with king/queen/double/twon bed...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,495,495,38751099,13046,HotelBeds,38751099-60,SUI.SU,SUITE SUPERIOR,Suite Superior,Suite Superior,...,1,Suite Superior,NaN,NaN,Suite,NaN,1.0,495,0,-same-
296,496,496,38751099,13046,HotelBeds,38751099-60,SUI.2D-SU,SUITE SUPERIOR 2 DOUBLE BEDS,Suite Superior,Suite Superior 2 Double Beds,...,2,Suite Superior 2 Beds,Double,NaN,Suite,2.0,2.0,496,0,-same-
297,497,497,38751099,13046,HotelBeds,38751099-61,SUI.B1,1-Bedroom Suite,"Suite, 1 Bedroom",1 Bedroom Suite,...,1,1 Bedroom Suite,NaN,NaN,Suite,NaN,1.0,497,0,does the sweet have a bedroom
298,498,498,38751099,13046,HotelBeds,38751099-61,SUI.B1-3,SUITE 1 BEDROOM,"Suite, 1 Bedroom",Suite 1 Bedroom,...,1,Suite 1 Bedroom,NaN,NaN,Suite,NaN,1.0,498,0,suite have a bedroom
299,499,499,38751099,13046,HotelBeds,38751099-61,SUI.B1-KG,SUITE KING BED 1 BEDROOM,"Suite, 1 Bedroom",Suite Bed 1 Bedroom,...,1,Suite King Bed 1 Bedroom,NaN,King,Suite,NaN,2.0,499,0,-same-

In [61]:
df1

,Unnamed: 0,room_type,ngrams,bed_count,bed_size,room_style,Vevotech Naming,hotelRoomType,no_of_person,Label,Remarks
0,200,Double Accessible,"['Double', 'Accessible', 'Double Accessible']",1,Single,Double,Accessible Room,Double Accessible,2,1,NaN
1,201,Room Accessible,"['Room', 'Accessible', 'Room Accessible']",1,Single,Standard,Accessible Room,Room Accessible,1,1,NaN
2,202,Room Club,"['Room', 'Club', 'Room Club']",1,Single,Standard,Club,Room Club,1,-1,Club rooms have more benefits than standard rooms
3,203,Double Club,"['Double', 'Club', 'Double Club']",1,Single,Double,Club,Double Club,2,-1,Club rooms have more benefits than double rooms
4,204,Double Club King Bed,"['Double', 'Club', 'King', 'Bed', 'Double Club...",1,King,Double,Club,Double Club King Bed,2,-1,Club rooms have more benefits than double rooms
...,...,...,...,...,...,...,...,...,...,...,...
395,395,Double Executive 2 Double Beds,"['Double', 'Executive', '2', 'Double', 'Beds',...",2,Single,Double,"Executive, 2 Double",Double Executive 2 Double Beds,2,0.0,NaN
396,396,1 King Bed Executive Nonsmoking,"['1', 'King', 'Bed', 'Executive', 'Nonsmoking'...",1,King,Standard,"Executive, King",1 King Bed Executive Nonsmoking,1,-1.0,no. of ppl should be 2
397,397,Quadruple Executive 2 Double Beds,"['Quadruple', 'Executive', '2', 'Double', 'Bed...",2,Single,Double,"Executive, Quadruple",Quadruple Executive 2 Double Beds,2,-1.0,2 Quadruple can accommodate 4 ppl
398,398,1 Kng Bed Leisure Nonsmoking,"['1', 'Kng', 'Bed', 'Leisure', 'Nonsmoking', '...",1,Single,Leisure,King Room,1 Kng Bed Leisure Nonsmoking,1,-1.0,no. of ppl should be 2
399,399,Double King Size Bed,"['Double', 'King', 'Size', 'Bed', 'Double King...",1,King,Double,King Room,Double King Size Bed,2,0.0,NaN

## Type A

In [103]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [105]:

style_size_dict = {
    'Deluxe': 'King',
    'Corner': 'Queen',
    'Standard': 'Single',
    'Suit': 'Twin Beds'
    
}

def extract_style_size(row):
    room_type = row['hotelRoomType']
    room_style = row['room_style']
    bed_size = row['bed_size']
    
    if not room_style and not bed_size:
        for token in nlp(room_type):
            if token.text in style_size_dict:
                bed_size = style_size_dict[token.text]
                room_style = token.text
                break
    
    elif not room_style:
        for token in nlp(room_type):
            if token.text in style_size_dict:
                room_style = token.text
                break
                
    elif not bed_size:
        if room_style in style_size_dict:
            bed_size = style_size_dict[room_style]
    
    row['room_style'] = room_style
    row['bed_size'] = bed_size
    return row

df = df.apply(extract_style_size, axis=1)

## Type B

In [ ]:
room_bed_dict = {
    "Standard": "King",
    "Deluxe": "Queen",
    "Suite": "King",
    "Executive": "King"
    
    # add more pairs
}

In [ ]:
for i, row in df.iterrows():
    if row['bed_size'] == '':
        room_style = row['room_style']
        if room_style in room_bed_dict:
            bed_size = room_bed_dict[room_style]
            df.at[i, 'bed_size'] = bed_size

In [ ]:
df.to_csv("test_3.csv")